### ISSUE TITLE
Rename <mm-app> to <mapml-viewer>

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#104]
`<mm-mapp>` is hard to remember, and it isn't self-descriptive. I see from the commit messages in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/91 that the intention was initially `<mm-app>`, which was later supposed to be changed to `<mm-map>`, but was actually changed to `<mm-mapp>` (notably https://geogratis.gc.ca/mapml/ still uses `<mm-app>`).

Can we settle on something more descriptive, that is easier to remember, and maybe more attractive to developers?
Perhaps `<map-embed>` or `<map-viewer>`?

A `<map->` autonomous custom element may also an option(?), but perhaps it's best to have something more distinguishable from `<map>`.

**Comment by Malvoz** [comment]
@prushforth what's your opinion on this?

I suspect I haven't been clear enough on the severity of the [accessibility issue](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/89#issuecomment-643657762) of `<map>`, and it is my opinion that it would be ethically irresponsible to promote any usage of `<map>` at this point. _The issue_ is equivalent of `<map style="display: none">` to sighted users.

I suggest we update the README.md to include instructions and example code using `<mm-mapp>` (hence why I'm eager for a name change) with a note that it is the **goal** to have the same capabilities ported to `<map>`.

**Comment by prushforth** [comment]
OK sorry it's taken so long to address.  I am willing but believe that the porting to `<map>` will get forgotten or discounted.

**Comment by prushforth** [comment]
@Malvoz certain influential parties have recently dumped on the whole MapML project. In consequence, I would prefer to name the custom element mapml-viewer, because I have put my guts into this one.  Would you be ok with that?

**Comment by Malvoz** [comment]
> I am willing but believe that the porting to `<map>` will get forgotten or discounted.

In worst case scenario, we still have a beautiful map component that is easy to use for developers.

> certain influential parties have recently dumped on the whole MapML project.

Interesting, it doesn't come as a total surprise, I'd like to learn more about their reasonings. Don't think we should be discouraged.

> I would prefer to name the custom element mapml-viewer, because I have put my guts into this one. Would you be ok with that?

Yes.

**Comment by prushforth** [comment]
> Interesting, it doesn't come as a total surprise, I'd like to learn more about their reasonings. Don't think we should be discouraged.

Thanks for your support, it means a *lot*.

Their reasoning is [here](https://ivan.sanchezortega.es:444/politics/2020/07/22/statement-mapml.html)

**Comment by prushforth** [comment]
`mapml-viewer` it is.  Ahmad, let's rename the dorkily-named `mm-app` to `mapml-viewer`, and show it some love in tests etc moving forward.  Once complete, I will proceed to update geogratis with the new viewer, which is a non-trivial task.

**Comment by prushforth** [comment]
We should focus our demo / index page usage on `mapml-viewer`.  We'll keep `web-map` around and maintained to some degree for reference and future discussion.
