### ISSUE TITLE
Design and implement the read-only <layer-> extent property

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#105]
Discussion of the [requirement](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/60)
Discussion of the [specification](https://github.com/Maps4HTML/HTML-Map-Element/issues/33)

**Comment by prushforth** [comment]
Per discussion: should this be an `<layer-> extent` property and not `bounds` since `bounds` is Leaflet specific and also has tcrs semantics?

**Comment by ahmadayubi** [comment]
Yeah good suggestion, currently it does return a leaflet bounds object, maybe this could be a change to add once M.Extent is established to show the change in logic (from L.bounds to M.Extent), but it could also be good to add preemptively, not sure.
