### ISSUE TITLE
Implement a <map>.extent property

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#110]
The `<map>` could reasonably have a dynamic `extent` property, similar to the (relatively, caveat DOM manipulation / changes) static `extent` property of the `<layer>` element.  It would reflect the bounds of the map in the various coordinate reference systems known to the map:

![image](https://user-images.githubusercontent.com/2437285/88208339-0fd6a880-cc1f-11ea-8e44-329d5d6e0492.png)

The `extent` could be calculated and set on move end.

[Requirement](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/60)
[Specification](https://github.com/Maps4HTML/MapML/issues/95) (discussion in `<layer>`)

**Comment by ahmadayubi** [comment]
Should it be a property thats updated on move end or should it be a method that returns the extents dynamically?

**Comment by prushforth** [comment]
Good question
