### ISSUE TITLE
Context menu over links on map should default to that of the browser, not the polyfill

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#127]
This was noticed by @malvoz, reviewer/contributor to [this](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/124#issuecomment-671989313) PR.  Since it was an existing issue not caused by that work, let's deal with it here.

**Comment by ahmadayubi** [comment]
I believe this may not be possible as the code snippet below shows, Leaflet either allows you to have an event handler for `contextmenu` or use the default browser context menu but not both. This means you can't have a listener for `contextmenu` events without disabling the browser menu. (This behavior only exists for `contextmenu` events)

leaflet-src.js :
![leaflet](https://user-images.githubusercontent.com/55214462/112211110-e3ca5780-8bf1-11eb-9e8d-4aca1aaa1b59.PNG)

**Comment by Malvoz** [comment]
Should we close this out as <q>invalid</q> then? Maybe we need a new label for <q>Blocked by upstream limitations</q>. 😋
