### ISSUE TITLE
Add debug mode to map

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#136]
Debug mode features needed:
- Tile grid overlay on top of map pane, with z: #, col:# , row# in top left corner of each tile
- Coordinate panel at the bottom left corner of the map that updates on mouse move, displaying the coordinates in tile, tilematrix, map, tcrs, pcrs, gcrs
- Rectangle overlay on each layer to display its layer bounds 

If anyone has any other suggestions please feel free to leave a comment.

**Comment by prushforth** [comment]
@bchagnon in particular I know you have good ideas about this kind of thing!
