### ISSUE TITLE
MapMLFeatures extent declaration using meta element not working as expected

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#147]
When declaring the extent of a mapMLFeature it should understand (and look for) the following meta element format:

`<meta name="extent" content="zoom=#, cs=######, top-left-vertical=#, top-left-horizontal=#, bottom-right-vertical=#, bottom-right-horizontal=#"> `

Where zoom is the zoom at which the extent points (top-left-vertical, etc.) are specified and cs is the coordinate system of those extent points.

**Comment by prushforth** [comment]
I added the demo/us_pop_density.mapml with values that reflect our discussion.
