### ISSUE TITLE
Localize the UI

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#149]
When the custom element is loaded in a browser, messages should be available in the locale of the browser.  We need to design a way to store and load localized messages, such as those used by the context menu, but more generally for all information that needs localization.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage

**Comment by Malvoz** [comment]
@prushforth Should we have a test page with right-to-left text directionality? I worry that [`dir="rtl"`](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute) (currently not a defined content attribute for mapml, probably should be) on either `<html>` or `<mapml>` may cause issues with `<coordinates>`/`<geometry>`, haven't done any testing though.

**Comment by prushforth** [comment]
@Malvoz 

> Should we have a test page with right-to-left text directionality just to check that everything works well including inline mapml. I think it could be as simple as setting [`dir="rtl"`](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute) (currently not a defined content attribute for mapml, probably should be) on `<html>` and/or `<mapml>`

Maybe?   Ahmad's on his last few days on the project so I want to help him get his latest PRs merged.  After that, I will be trying to get ready for the workshop, so this may have to be a bookmark for a little while...

**Comment by ahmadayubi** [comment]
Some resources that may be of value in the future:
- [PolyglotJS - by AirBnB](https://airbnb.io/polyglot.js/)
- [i18nJS - ](https://i18njs.com/)

I think the usual design pattern is to store translations in a seperate json file that is loaded in using a library like PolyglotJS, which manages the loaded content. In our case there are only a handful of translations needed so I'm wondering if having the additional features these libraries provide is worthwhile or if a native approach would be more efficient. Not sure.

**Comment by Malvoz** [comment]
It should be noted that keyboards suited for other languages than English can have totally different layouts, so keyboard shortcuts may have to be adapted as well, for a fully localized UI.

**Comment by Malvoz** [comment]
It should be noted that [CSS Logical Properties](https://www.w3.org/TR/css-logical/) enables "layout through logical, rather than physical, direction and dimension mappings", which would go a long way in setting up the UI for internationalization (more info/demo/examples here: https://web.dev/logical-property-shorthands/). I'd be _very_ surprised if Leaflet actually decided to support it in the future however...

**Comment by Malvoz** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language

Also, the SVG [`systemLanguage`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/systemLanguage) attribute is pretty cool (see [demo](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch#svg_switch_example)), although I'm not quite sure it'll be needed in practice.

**Comment by prushforth** [comment]
I think that this can be closed, since the [extension supports locales](https://github.com/Maps4HTML/mapml-extension/tree/main/src/_locales).  There may be other aspects to this, besides menus, so re-open and discuss as required.
