### ISSUE TITLE
Resources should be minified

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#153]
Google's [Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en) reports a potential saving of 148.6 kb in transfer size (not including CSS):

<img width="600" src="https://user-images.githubusercontent.com/26493779/91040090-f229a400-e60d-11ea-858e-a527b42c54a9.png">

We should:

- [ ] Uglify all JS files
- [x] Minify and concatenate CSS files (fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/606)

Of course, license text should be preserved.

**Comment by ahmadayubi** [comment]
A minified version of mapml is provided in the build branch and in releases, but having a minified version of the other javascript files would be good too.

**Comment by Malvoz** [comment]
> A minified version of mapml is provided in the build branch and in releases

@ahmadayubi Is `mapml.min.js` used anywhere?

Would it be acceptable to simply uglify/minify everything in the `dist` folder without outputting `.min.(js|css)` file names?

**Comment by ahmadayubi** [comment]
It's currently not used anywhere in the tests and experiments as people usually debug on those files so it's important they can read it (without having to pretty print in chrome debugger), you could definitely minify everything but it would add an extra step to debugging. 

It wouldn't be a big deal though, it's mostly a preference thing I believe. @prushforth has developed the minification process through GruntJS, maybe he could shed light on his decision to offer both .min.js and .js

**Comment by Malvoz** [comment]
> you could definitely minify everything but it would add an extra step to debugging.

Unless we generate [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) using grunt-contrib-uglify's [sourceMap](https://github.com/gruntjs/grunt-contrib-uglify/blob/main/docs/uglify-options.md#sourcemap) option?

**Comment by ahmadayubi** [comment]
That would definitely work (after setting up and testing to make sure it works as expected), I hadn't considered using source maps in the past.

**Comment by prushforth** [comment]
Addressed by https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/705
