### ISSUE TITLE
Remaining FOUC

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#154]
Stylesheets created from scripts aren't render-blocking, thus if you load a page with the map viewer on it, and the resources aren't in the cache already you'll see FOUC (sigh). Below is a screenshot of loading the [Toporama MapML Service preview](https://geogratis.gc.ca/mapml/en/osmtile/toporama/) on "Slow 3G" (using dev tools), which makes it super apparent that styles (`leaflet.css`, `mapml.css`) haven't loaded in time:

<img width="450" src="https://user-images.githubusercontent.com/26493779/91041072-aed03500-e60f-11ea-9bc8-dc89205b2da5.png">

**Comment by Malvoz** [comment]
There may potentially be many different ways of mitigating/fixing this. Unfortunately we can't apply the [pre-styling technique](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/0cf0de4f5917fb691d222b3dbf7f92766e65f3c1/index-mapml-viewer.html#L34-L37) using [`:defined`](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined) here because the affected elements aren't custom elements.

I believe one approach would be to ask the author to include an accompanying `<link rel="stylesheet" href="mapml-viewer.css">` together with the current `<script type="module" href="mapml-viewer.js">`.

The new `mapml-viewer.css` would (somehow be generated from) and include all the styles of, and replace this:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/0cf0de4f5917fb691d222b3dbf7f92766e65f3c1/src/mapml-viewer.js#L94-L98

This approach also has the benefit in that it would allow us to also bake in the [pre-styling/FOUC mitigating styles](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/0cf0de4f5917fb691d222b3dbf7f92766e65f3c1/index-mapml-viewer.html#L34-L44), so that authors would get free FOUC mitigation of the map element/(inline) layers/fallback content without requiring them to add those styles in separately.

Additionally the [default map styles](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/0cf0de4f5917fb691d222b3dbf7f92766e65f3c1/src/mapml-viewer.js#L103-L122) could go into that same stylesheet, while this means higher CSS specificity than we currently get from `:host` I think most (all?) authors would agree that zero FOUC is better than having to add a CSS class to override the default map styles.

**Comment by prushforth** [comment]
If I recall correctly, the reason the template contains the leaflet.css, leaflet.fullscreen.css and mapml.css is to scope the styles to within the custom element.  Including styles in the host document won't affect shadow DOM content, which is what these stylesheets control.

**Comment by Malvoz** [comment]
You're right, scratch https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/154#issuecomment-679114959, it amazes me how I could have neglected that aspect.

**Comment by Malvoz** [comment]
Removing the label "Bug", I think this is merely an inconvenience.

**Comment by Malvoz** [comment]
This was to some degree fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/164/commits/d286f6d9ccd22d973cbc7d8e9e70b505b971cf24. There are comments in the JS/CSS files about the `visibility` hack for others to find, and perhaps improve upon. Closing this for now.
