### ISSUE TITLE
Layer control should not be visible if no layers exist, or all layers are `hidden`

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#159]
Consider the following:

```html
<mapml-viewer projection="CBMTILE" zoom="2" lat="61.2091250" lon="-90.8508370" controls>
  <layer- hidden
    label="Canada Base Map - Transportation (CBMT)" src="http://geogratis.gc.ca/mapml/en/cbmtile/cbmt/" checked>
  </layer->
</mapml-viewer>
```

Below is a screenshot of hovering a mouse pointer over the layer control in a map with the given HTML:

![layers](https://user-images.githubusercontent.com/26493779/91362197-44c7b380-e7fa-11ea-9875-29bdcc1c06f9.png)

As there are no items in the layer control's list to be displayed, I believe the layer control itself should be hidden from the user.

**Comment by prushforth** [comment]
I agree, this is a bug. Thanks for reporting it.
