### ISSUE TITLE
Fullscreen control not working on touch devices

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#162]
The fullscreen control doesn't initiate fullscreen mode in some browsers on touch devices/touch simulation.

Repro steps:

1. Go to https://geogratis.gc.ca/mapml/en/osmtile/cbmt/
2. Open devtools, Toggle Device Toolbar in Chrome or turn on Responsive Design Mode in Firefox (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>M</kbd>)
3. Refresh the page then press the fullscreen control

**Comment by Malvoz** [comment]
I tested installing the official (but unmaintained) Leaflet.fullscreen, still the same issue. The control works in their [demo](http://leaflet.github.io/Leaflet.fullscreen/) when reproducing the above steps, so it's an issue with this build only.

**Comment by prushforth** [comment]
Seems to work on my Pixel 4 Firefox, but not working on blink browsers.

**Comment by ahmadayubi** [comment]
I tried it on chrome, firefox, edge and duckduckgo browser on pixel 2 xl and they all worked. I also tried the chrome device toolbar in my laptop browser and that worked too.

@prushforth you mentioned it doesn't work on blink browsers, any in specific? I believe chrome is a blink browser and it worked in my case.

**Comment by prushforth** [comment]
Chrome is def a blink browser, so is new Edge and Brave browser.  Let me see if my results have changed since Sept.

**Comment by prushforth** [comment]
Nope, on chrome, the device does not recognize the touch event on the fullscreen icon on geogratis.

Tried in Firefox, it works.

**Comment by prushforth** [comment]
Does not work in new edge either, whereas the +/- buttons just adjacent to it *do* work.  That might be a clue.

**Comment by prushforth** [comment]
If I understand correctly, the fullscreen mode is limited to secure domains.  While the lock icon does come up for that domain, perhaps it is mixed content or something that chrome sees that ff isn't seeing that disables the fullscreen mode on chrome.

**Comment by Malvoz** [comment]
> perhaps it is mixed content

Good thinking, I can see how that could cause the issue, although that doesn't seem to be the case. In Chrome it's easy to spot mixed content, e.g. see console warnings for https://active-mixed-content.glitch.me/ (found the link in https://web.dev/fixing-mixed-content/).

**Comment by Malvoz** [comment]
`mapml-viewer.js` served at https://geogratis.gc.ca/mapml/en/osmtile/cbmt/ is a bit outdated at this point, I suppose we can close this issue as I can't reproduce with the demo pages.

**Comment by prushforth** [comment]
Darn - that's my fault.  Sorry to waste your time.

**Comment by Malvoz** [comment]
No worries Peter, perhaps I shouldn't have filed a bug against geogratis.gc.ca. If the bug resurfaces we'll just re-open this 😋

**Comment by prushforth** [comment]
Dreaming of a hosted service at maps4html.org... 

In the mean time, I updated the code on geogratis.  Hopefully the fullscreen bug will disappear.

**Comment by Malvoz** [comment]
Confirmed, no bug on geogratis! 👍

**Comment by ahmadayubi** [comment]
Maybe we can use [Heroku](https://www.heroku.com/). I've used it in the past, it rebuilds the src on every push/PR to the repo and works really well. Only down side to the free version is that it takes a few seconds to load when it cold starts.
