### ISSUE TITLE
Create a map "back button" control that can be used to back out of map actions

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#17]
Analogous to the browser back button.  Think about / research the API for this, how it can be exposed to JavaScript.

**Comment by bchagnon** [comment]
Leaflet plugin http://cscott530.github.io/leaflet-history/ from https://github.com/cscott530/leaflet-history

**Comment by prushforth** [comment]
Added as task in the context menu [issue](#18)
