### ISSUE TITLE
Create a right-click / context menu for the map element

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#18]
Should be included as a [Use Case in the Use Cases and requirements document](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/6).

- [x] View Source
- [x] Back button
- [ ] Save as image
- [x] Coordinates
- [ ] [View layer metadata](https://github.com/Maps4HTML/MapML/issues/36)

**Comment by Malvoz** [comment]
- [ ] Show/hide Controls (available in both Chrome and Firefox for `<video>`)
- [ ] [Fullscreen](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/83) (available in Firefox for `<video>`)
