### ISSUE TITLE
When map controls are toggled off, the layer's disabled attribute does not update

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#190]
Since MapMLLayerControl is responsible for attribute updates to the elements in terms of layer's having a disabled attribute, if the controls are not on the map the attribute updates don't occur and can't be observed by a MutationObserver. This updating can be seen below on lines 111 and 116:
https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/4098aa007495e527ead03ab737e9a4caae21ebe1/src/mapml/layers/ControlLayer.js#L110-L119

**Comment by prushforth** [comment]
A mutation observer on the `<layer disabled>` property should be observable, shouldn't it?

**Comment by ahmadayubi** [comment]
It's observable but the problem is it doesn't update (update the layer element) if the map doesn't have controls toggled on.

Line 111 sets the disabled attribute on the layer element while
Line 112 sets disabled on the layer control menu item
