### ISSUE TITLE
Projection negotiation fails

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#209]
When you drag the URL of a map layer in a different projection than that of the map, if that mapml document has several <link projection="..." rel="alternate" ...> links in it, the following error occurs:

Uncaught ReferenceError: FALLBACK_PROJECTION is not defined
    at HTMLElement._validateDisabled (layer.js:189)
    at NewClass.fire (leaflet-src.js:612)
    at NewClass.removeLayer (leaflet-src.js:6677)
    at HTMLElement.disconnectedCallback (layer.js:88)
    at HTMLElement.set src [as src] (layer.js:32)
    at HTMLElement.<anonymous> (layer.js:306)
    at NewClass.fire (leaflet-src.js:612)
    at XMLHttpRequest._processInitialExtent (mapml.js:2728)

Steps to reproduce

1) Open web-map-custom-element/index.html (which has a CBMTILE map with one layer)
2) Drag a link from a GeoServer Layer Preview MapML link onto the index.html (these all have alternate projection links)

There may be an easier way to obtain a URL to a MapML document with such a configuration (i.e. make one by hand), this is just the way I discovered it.

When you fix this, please create a test case to cover it. Thanks!

**Comment by ahmadayubi** [comment]
The Uncaught ReferenceError: FALLBACK_PROJECTION is not defined problem is resolved in the latest PR, that issue specifically was due to an invalid import as layer.js is not part of rollup. I'd have to test if projection negotiation works the same but the reference error should not show in that PR.

**Comment by prushforth** [comment]
Thanks, I have used that PR code and it does fix the issue.  Still would be great to add some test coverage for projection negotiation.  Closing this in light of your previous work on it :-)
