### ISSUE TITLE
Drag and drop behaviour of layers in control

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#248]
Currently, the [layer control does nothing with drop events](https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/), they are passed on to the map.  So, if you drag a layer in the layer control to another position in the stack, it simply copies the layer on top of the map.  Useful sometimes, but not if you don't intend for it.

It would be nice to be able to re-order layers by dragging their layer control entry up or down.  This would require updating the position of the `<layer->` element in the DOM as a consequence of the event, and preventing the event from further propagation (to the map) and consequent node (`<layer->`).

Your thoughts appreciated below, especially with regard to the keyboard operation of this facility (is that possible even).

**Comment by Malvoz** [comment]
I've collected a few resources regarding keyboard accessibility of drag and drop:
 
- Accessibility & Native Drag and Drop: http://html5doctor.com/accessibility-native-drag-and-drop/
- Best practices: https://www.w3.org/wiki/PF/ARIA/BestPractices/DragDrop
- The dedicated ARIA attributes: https://www.w3.org/TR/wai-aria-1.1/#attrs_dragdrop

If keyboard accessible drag and drop would prove to be complicated or cumbersome, that aspect can always be deferred.

**Comment by Malvoz** [comment]
The ARIA Authoring Practices doc doesn't have any guidelines for drag and drop (https://github.com/w3c/aria-practices/issues/1284), and authors are advised to treat the attributes as deprecated as they're planned to be replaced, per a note in their respective definitions. Even if they work today, they may not in the future, so probably not worth spending time on.
