### ISSUE TITLE
Grabbing cursor not showing

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#250]
Leaflet.css uses a `.leaflet-dragging .leaflet-grab` selector to set `cursor: grabbing`, this is currently not working because `leaflet-dragging` is set on the document `body` element (cross shadow boundary).

https://user-images.githubusercontent.com/26493779/105248730-36967d00-5b77-11eb-8b73-2017f7df2566.mp4

**Comment by prushforth** [comment]
Why is leaflet-dragging set on body do you suppose?

**Comment by Malvoz** [comment]
@prushforth https://github.com/Leaflet/Leaflet/issues/2164#issuecomment-27944701 suggests that they're using it to show the grabbing cursor when the mouse pointer goes outside the map view, however that doesn't seem to work when testing here: https://leafletjs.com/examples/quick-start/example.html.


And people continue to report [performance issues](https://github.com/Leaflet/Leaflet/issues/2164#issuecomment-45768405) due to the reflow/repaint triggered by setting/removing the class on the body element. 😕
