### ISSUE TITLE
Allow user to remove layer from (DOM) map / layer control

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#253]
This is just an idea for discussion. 

It might be useful to allow the user to not just remove a layer from the map (checked), but to remove the layer from the DOM altogether, e.g. click X to delete it from the layer control. It might be confusing though too, so maybe not.  Please add your  thoughts below.

Does such an idea affect requirements, or specifications?

**Comment by Malvoz** [comment]
I agree with this, especially if users can add their own layers.

Here's a quick mockup of a potential UI (using `display: flex` and `align-items: center` on the `summary` element, with a new sibling to the `label` element):


![delete-layer-button-mockup](https://user-images.githubusercontent.com/26493779/105503791-4cb35300-5cc7-11eb-8b94-446c2c454d20.png)

It should ideally be a button (whether `<button>` or `<a role="button">`) with ARIA properties such as `aria-label="Delete layer"` and maybe `aria-controls="{ID-of-parent-fieldset-el}"`. Perhaps the delete button should only be visible when its parent `fieldset` recieves `:hover` and [`:focus-within`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)?

> Does such an idea affect requirements, or specifications?

This is an implementation detail that probably should not be subject to the UCR report. I do think this is worthy of mentioning in the spec, along with other descriptions of the UI of the individual controls.

**Comment by Malvoz** [comment]
Should it be possible to restore a deleted layer? Maybe I deleted the wrong one and I want it back without refreshing the page?

**Comment by ahmadayubi** [comment]
I think the reload was intended to just reset history and return to the initial location, it doesn't reset any other properties so I don't think it should reset the initial layers either.

**Comment by ahmadayubi** [comment]
Also do you have the code for your mockup somewhere? It's a good UI implementation .

**Comment by Malvoz** [comment]
> Also do you have the code for your mockup somewhere?

I don't, I was just messing around with it 😋 It'd probably need changes per https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263 anyway.
