### ISSUE TITLE
`<tiles>`?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#265]
I saw a `<tiles>` element in some of the test or demo pages, it doesn't exist in the spec, should it be added? Also, maybe it could be  named more distinctively from `<tile>`, e.g. `<tilegroup>`?

**Comment by prushforth** [comment]
Yes, I think this was not necessary.  This element was added to the shadow DOM, and although it is or was likely used in some way by my code, I don't think it desirable to propose to add it to the HTML language, at least not at this time.

**Comment by ahmadayubi** [comment]
It was originally just using a `<div>` but along the way it was suggested that it should use `<tiles>` instead, it should be able to revert back to `<div>` pretty straightforwardly, if `<div>` is the appropriate container to use in this case.

**Comment by prushforth** [comment]
I guess it would be fine to revert to div, but again because it's an "implementation detail", I don't think it's high priority to do so, and indeed it may add value / clarity for ourselves as implementers while debugging, although at the cost of some confusion as to what's in scope of the proposal vs what's out of scope.

**Comment by Malvoz** [comment]
> Even in a native browser implementation, they will likely find it necessary to implement (internal) abstractions that allow rendering of spatial information appropriately.

I _think_ it's important that such implementation details are standardized, otherwise authors may suffer from interoperability issues and may be stuck with [vendor prefixes](https://www.w3.org/TR/css-2020/#vendor-prefix) to [style maps](https://github.com/Maps4HTML/MapML/issues/71), etc.

Anyhow, `<tiles>`:
- > could be named more distinctively from `<tile>`, e.g. `<tilegroup>`?
-  Should be a custom element (e.g. `<tile-group>`) or `<div>` (with a class of `mapml-tilegroup` for example), per issue: https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/174.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/515/.
