### ISSUE TITLE
Queryable layer bounds not working as expected

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#266]
When a user clicks outside the bounds of a queryable layer the popup still shows up. I think it's expect the popup only shows within the bounds. 

https://user-images.githubusercontent.com/55214462/106167290-0b092900-615b-11eb-8a59-63ae0475852e.mp4

**Comment by prushforth** [comment]
Seems like an oversight on my part.
