### ISSUE TITLE
query link response without <extent> element doesn't draw

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#271]
Noticed when updating geoserver code, if I remove the <extent> element from a query response mapml document, the  feature doesn't draw (apparently).

**Comment by ahmadayubi** [comment]
Don't `<link rel="query|tile|image">`  need to exist within an `<extent>`, I've only ever seen it within an `<extent>` or are there cases where they aren't?

**Comment by prushforth** [comment]
> Don't `<link rel="query|tile|image">` need to exist within an <extent>, I've only ever seen it within an <extent> or are there cases where they aren't?

Yes, but that's not the issue.  It's hard to show without geoserver running, but if when a query  event happens the *response* doesn't contain **at least** an empty `<extent>` element, the feature doesn't get highlighted.
