### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#283]
I have been thinking about how we should go about documenting what is supported by the polyfill, apart and aside what is specified.  Also, many people , myself included, find it easier to read developer oriented documentation than specs, which should be for implementers.  

To that end, I'd like to start a discussion and selection of a documentation vehicle that is compatible with what resources we're using (primarily GitHub pages at this time, i.e. access to servers etc is limited).

To kick off the discussion, I'd say that it would be good to have our polyfill documented like the documentation of similar and related APIs per the MDN platform.  Recently, they migrated from a platform that didn't lend itself to GitHub pages, [to one that apparently does](https://hacks.mozilla.org/2021/01/welcoming-open-web-docs-to-the-mdn-family/).  Let's have a look at Yari to see if we could use that tool as a basis for our own documentation.

Discuss below!

**Comment by ahmadayubi** [comment]
At first glance it appears Yari would require a server as GitHub Pages only serves static content. Yari seems to be a server-side platform that dynamically creates webpages based on the content of a separate repository using Node + ExpressJS.

If limited to GitHub Pages you would need to use something like https://v2.docusaurus.io/ I believe.
