### ISSUE TITLE
iframes for query responses can execute scripting

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#284]
[CSP Embedded Enforcement](https://w3c.github.io/webappsec-cspee/) (defines the iframe `csp` attribute) [isn't supported by all major browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/csp#browser_compatibility), so we fail to prevent scripts from executing in unsupporting browsers. Additionally, scripting is also executed in Chrome due to a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1163174) where about:srcdoc fails to inherit the policy.

There are at least 2 ways to go about blocking scripts with wide support:
1. Prepend `srcdoc` with `<meta http-equiv="content-security-policy" content="script-src 'none';">`
2. [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) the iframes

I think option 1 is more straight forward, and doesn't have any further implications other than blocking scripts, if that's what we want to do.

**Comment by Malvoz** [comment]
For clarity, I'm referring to:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/ad3f1fd1f5498e0ae7b3e03c555899763142d2fb/src/mapml/handlers/QueryHandler.js#L155

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/ad3f1fd1f5498e0ae7b3e03c555899763142d2fb/src/mapml/handlers/QueryHandler.js#L170

**Comment by ahmadayubi** [comment]
Alright I'll implement option 1 in an upcoming PR related to issue #282

**Comment by Malvoz** [comment]
As a side note for option nr. 1, authors of the content inside the iframe can't loosen the policy (to re-enable scripting) by setting their own `<meta>` CSP, as multiple `<meta>` CSP policies can only be used to further strengthen an already defined policy (described in https://w3c.github.io/webappsec-csp/#multiple-policies). 👍🏼

**Comment by Malvoz** [comment]
FWIW option 1 (as opposed to option 2) does not block scripts from executing in nested iframes. But I believe only designated MapML elements are allowed in `<feature>`, in that case it might not be an issue.
