### ISSUE TITLE
MapML to various JS web map libraries converter  

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#298]
The idea of a MapML to LeafletJS, OpenLayers, etc. converter was brought up. It might be useful in showing the contrast between using MapML syntax in comparison to the existing web mapping libraries. 

Feel free to make any suggestions or raise concerns.

**Comment by prushforth** [comment]
It might be out of fashion, but this is exactly what XSLT was designed for: to transform declarative markup into diverse forms, with extra, format-specific semantics provided by and built into the transform.  XSLT will still be cool until it's torn from my cold dead hands.

**Comment by ahmadayubi** [comment]
XSLT does should perfect for the job if this idea is ever implemented, there would be a learning curve as it is brand new technology for me at least.

**Comment by prushforth** [comment]
You will love it, guaranteed

**Comment by prushforth** [comment]
There's the [qgis2web](https://www.igismap.com/qgis2web-create-web-maps/) QGIS [plugin](https://plugins.qgis.org/plugins/qgis2web/) that can take a QGIS project and save it as either Leaflet or OpenLayers Web map.  I've also wanted to play around with this to see if it was possible to save a QGIS project as a MapML map.  I imagine the plugin  might need to use the facilities of both [custom projections](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/227) as well as some version of the "[Leaflet API Façade](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/299)".

**Comment by ahmadayubi** [comment]
Isn't there already a plugin to export as mapml or does that have different functionality? Also it would be interesting to have such a plugin but it also seems like a highly specialized tool as most ordinary folks don't really use QGIS unless that is the intention, to get specialized users to use it.

**Comment by prushforth** [comment]
I believe the qgis2web plugin is for GIS people who don't want to learn the details of Web development bit who do want to publish their GIS project to the Web. MapML is meant to be a bit of a bridge for those people, making Web mapping simpler to understand (the basics, anyway). So having support for mapml-viewer maps might make it easier for them to read and understand the basics. Having really complex output might defeat that goal but anyway, the workflow this issue suggests is similar to the qgis2web workflow: make a map in one medium, and run a translator to generate the same map in another "language", or medium. 

The Web is supposed to replace all other media, so the idea behind MapML is to build maps into that medium.

**Comment by Malvoz** [comment]
Is this supposed to be used for comparison _only_ or are mapml-viewer users supposed to be able to choose which underlying framework is used in the maps they embed? Each library comes with its own set of issues, specifically in regards to accessibility.
