### ISSUE TITLE
Focus controls popup button doesn't function when all controls are disabled.

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#303]
In the case where all controls are disabled (no zoom, fullscreen, reload or layer control buttons) where should the focus go when Focus Controls button is pressed (`>|`)?

Currently this causes an error.

![nocontols](https://user-images.githubusercontent.com/55214462/108258954-92303800-712e-11eb-9398-dcf9e7c46759.png)

**Comment by Malvoz** [comment]
I think the most logical thing would be to disable that button if controls are toggled off.

**Comment by ahmadayubi** [comment]
So while tabbing it would skip over the button and go straight to the `x` button. That sounds reasonable to me.

**Comment by Malvoz** [comment]
Yes it could be taken out of the tab order by setting `tabindex="-1"`, or `aria-disabled="true"` if we want to convey that "here is a button, but it is currently disabled".

**Comment by prushforth** [comment]
The attribution control is always present, so you should go to the first link in there, I think.
