### ISSUE TITLE
`mix-blend-mode`

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#305]
Is [`mix-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) useful? How does it compare to current use of `opacity`?

The following video showcases the different [blend modes](https://developer.mozilla.org/en-US/docs/Web/CSS/blend-mode) by applying the values to all `.mapml-layer` elements (I had to apply `.leaflet-layer * {mix-blend-mode: inherit; }` since it's not an inheritable property):

https://user-images.githubusercontent.com/26493779/108525122-0d7d1f80-72d0-11eb-8d82-babff23d2ebe.mp4

Other related CSS properties include: [`background-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode) and [`isolation`](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation).

Maybe options for changing blend modes could exist along with opacity in the UI, or otherwise we could have some documentation in web-map-docs for how to enable this.

**Comment by prushforth** [comment]
I am pretty certain this will be / is useful for cartographers, but I'm not an expert, especially when combining features within a single layer.

**Comment by Malvoz** [comment]
> How does it compare to current use of `opacity`?

While opacity is simpler to work with, it's usage - which I believe is mainly to "blend" (wink wink) layers  - causes the layer with reduced opacity to essentially be less visible. Conforming to WCAG success criteria for contrast ([1.4.3 Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum), [1.4.6 Contrast (Enhanced)](https://www.w3.org/TR/WCAG21/#contrast-enhanced), [1.4.11 Non-text Contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast)) can be hard or even impossible depending on the applied opacity.

**Comment by Malvoz** [comment]
TBD: open UCR issue(s) to discuss the use case(s) of changing opacity/blending of layers.

**Comment by Malvoz** [comment]
> TBD: open UCR issue(s) to discuss the use case(s) of changing opacity/blending of layers and/or features.

Opened an issue to discuss the Capability: https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/247.

I'm closing this for now. We can revisit this at a later time if needed to satisfy user preferences, as suggested in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/305#issuecomment-782175723.
