### ISSUE TITLE
Double check point features, might be referencing incorrect directory for marker PNG

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#307]
The viewer keeps the leaflet markers in an images folder in dist, but when a point is created it may be referencing the incorrect directory internally. Resulting in a 404 error when trying to load in the marker png.

**Comment by Malvoz** [comment]
I think the related Leaflet issue is https://github.com/Leaflet/Leaflet/pull/6951.
