### ISSUE TITLE
Toggling a layer in the layer control causes map to zoom in

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#309]
I'm seeing an issue in layerContextMenu.html that I wasn't able to reproduce in a couple of other maps:

<table><td width="400"><video src="https://user-images.githubusercontent.com/26493779/109057647-4824f480-76e2-11eb-849e-dc0688bcfcfe.mp4"></video></td></table>

**Comment by ahmadayubi** [comment]
When a layer is removed leaflet zooms into the maps new zoom range, so say you have layers:
1. zoom range = (0, 4)
2. zoom range = (1, 4)

If the map is at zoom level 0 and layer 1 is removed/deselected then the map zooms to zoom level 1.

In the video example, when you remove the first layer the maps zoom range gets updated from (0, 25) to (4,25) so it zooms in.
More of a feature than a bug so I'm going to close this issue. If you have questions about it feel free to ask.
