### ISSUE TITLE
Internationalization API

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#315]
If browsers implemented a `<map>` and `<layer>` element suite per the MapML proposal, each browser would be responsible for providing an internationalization of the widget interface.  That is, each browser would have to provide the localized text strings for menu items and user interface labels.  I think we should simulate such internationalization by allowing the user to choose the language of the UI from a control embedded within the widget. The UI language strings of supported languages would be read from a file or data structure built into the widget.  We should constrain the list of languages to be more than one but quite small for the time being, so as not to bloat the widget code downloaded at runtime.

**Comment by Malvoz** [comment]
Is this different form https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/149?

**Comment by prushforth** [comment]
Ah nope
