### ISSUE TITLE
The 1px gap between tiles

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#324]
There's a bug causing a 1px gap between tiles in some browsers (as you may or may not have noticed):

<img width="400" src="https://user-images.githubusercontent.com/26493779/109212020-512fc780-77af-11eb-811a-a9e58af409e7.png" alt="1 px gap between tiles">

The relevant Leaflet issues are: https://github.com/Leaflet/Leaflet/issues/3575 and https://github.com/Leaflet/Leaflet/issues/6101. Leaflet users filed browser bugs with [WebKit](https://bugs.webkit.org/show_bug.cgi?id=156130) and [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=600120) but they haven't been fixed in many years so I don't think that's gonna change anytime soon.

There has been multiple proposed hacks/fixes (even Chrome people suggested fixes in https://bugs.chromium.org/p/chromium/issues/detail?id=600120#c15).

I tried one simple hack proposed in the original Leaflet issue that probably isn't very reliable as is:

```css
.leaflet-tile-container img {
    width: 256.8px !important;
    height: 256.8px !important;
}
```

<img width="400" src="https://user-images.githubusercontent.com/26493779/109212206-85a38380-77af-11eb-87b2-d3058dce4ed7.png" alt="1 px gap between tiles CSS fix">

The hack fixes the gap issue in browsers that are affected by this bug, but causes tiles to overlap (I think) in browsers that don't have the bug, e.g. Firefox (tab to the right implements the CSS hack, tab to the left does not):

<table><td width="500"><video src="https://user-images.githubusercontent.com/26493779/109215224-26e00900-77b3-11eb-989c-56e14bb39ec7.mp4"></video></td></table>

Ivan Sanchez created the [Leaflet.TileLayer.NoGap](https://github.com/Leaflet/Leaflet.TileLayer.NoGap) plugin to fix the bug, but from comments in the Leaflet issue it seems it may not be compatible with later Leaflet versions.

WDYT? Is it worth to attempt to fix this bug?

**Comment by prushforth** [comment]
It is an annoyance, and thanks for doing all that digging on it.  I don't think it's worthwhile solving at this time, since we're working on "how could this work as a standard" more than trying to develop a product.
