### ISSUE TITLE
Tabbing through features has a hiccup - skip block gets stuck between set of polygon and point features

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#325]
Steps to reproduce

Visit this [experiment](https://maps4html.org/experiments/index.html), which has a set of features in the DOM. Press Tab twice, the first polygon feature (quite small) should be focused. Hit Enter.  Hit Tab 3x to focus the ">" affordance. Hit Enter.  The second polygon feature should be focused. Hit Enter, then Tab 3x, then Enter. The third polygon feature should be focused. Hit Tab 3x, then Enter.  The focus **should** go to the fourth feature (a point) but it does not, it stays on the Prescott Hotel, a very fine Italian eatery and tavern.  You need to hit Tab to get to the fourth feature.

Edit: In playing with the ">" affordance more, when the set of features in focus contains points, the "<" and ">" don't seem to focus the next or previous feature reliably, you always need to add a Tab or Shift-Tab to get focus to where you want.

**Comment by ahmadayubi** [comment]
This is probably due to the manual nature of focus, it only accounts for features that use `<path>` and not `<img>`, as those are not in the same pane.

**Comment by prushforth** [comment]
See, that's why standards are important

**Comment by ahmadayubi** [comment]
Right, its a difference between Leaflet and MapML abstractions. With the viewer it'll be challenging forcing it to conform to MapML abstractions since it's built on Leaflet.

**Comment by prushforth** [comment]
You don't see this problem when you hit tab, by the way, the tab sequence seems correct. It's just with the "previous" and "next" affordances.

**Comment by prushforth** [comment]
Also, the brain dead rendering approach I used with points maps them to Leaflet markers, which is not too flexible.  Would be better realized as some svg rendering, I think.  Maybe @shepazu  or @AmeliaBR  can advise.

**Comment by ahmadayubi** [comment]
When you hit tab it won't be in document order, it'll be in the leaflet pane order. 
![order](https://user-images.githubusercontent.com/55214462/109315503-9c31f500-7818-11eb-818a-4a8f12414acb.png)

So if you had a point before a polygon in a mapml file, the polygon would still focus first as that pane comes before the marker pane.

**Comment by ahmadayubi** [comment]
> Also, the brain dead rendering approach I used with points maps them to Leaflet markers, which is not too flexible. Would be better realized as some svg rendering, I think. Maybe @shepazu or @AmeliaBR can advise.

You could create a custom marker layer that extends L.polygon and create an svg marker that doesn't scale with zooms.
