### ISSUE TITLE
Change popup behaviour so that the map pans when the popup extends past the viewport.

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#337]
Mentioned as a problem in #335.  Also, if possible via Leaflet popup options, make the popup stay on screen until dismissed (don't disappear on pan).

**Comment by ahmadayubi** [comment]
It's not possible to keep the popup on pan. The way mapml handles drawing the features means it removes the feature on map and readds them. When it's removed the popup is closed. I guess you could reopen the popup but that seems really janky, but can still be done if you want.

**Comment by prushforth** [comment]
I think you can make the map pan if the pop-up would overflow: https://leafletjs.com/reference-1.7.1.html#popup-autopan

**Comment by ahmadayubi** [comment]
Yes you can do that, but when the moveend event occurs it removes all the polygons, lines, etc. which understandably removes the popups also.

**Comment by prushforth** [comment]
Huh weird

**Comment by ahmadayubi** [comment]
I'll refactor moveend and go that route.

**Comment by prushforth** [comment]
Ok hopefully not too much work or bugs there
