### ISSUE TITLE
Set geometry colour to strong, bold value when focus is on it.  

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#338]
Mentioned in #335.

**Comment by Malvoz** [comment]
Implementing this is sort of indicative of `<feature>` elements having a default CSS `stroke` and `stroke-width` (or however the styling of `<feature>` would be mapped to) on focus, which I think is a bit odd, that's what `outline` is for.

If outlines aren't sufficient then that's a problem with the user agent.

There's a 17 year old Mozilla bug on implementing clearer outlines: https://bugzilla.mozilla.org/show_bug.cgi?id=251198, which I think is blocked on outlines being "ugly". And here's a 21 year old bug specific to MacOS: https://bugzilla.mozilla.org/show_bug.cgi?id=53927.

I don't oppose fixing this on our end, but they're really browser bugs.
