### ISSUE TITLE
Error loading pcrs coordinates for features

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#344]
![image](https://user-images.githubusercontent.com/2437285/110386611-81d4f400-802e-11eb-85aa-18afaf5c489c.png)

Steps to reproduce:

Fork this [branch ](https://github.com/prushforth/Web-Map-Custom-Element/tree/pcrs-geometry-bug)
Build project, run localhost server
Load index.html in browser with console open

**Comment by ahmadayubi** [comment]
Should this issue be addressed now or should it be postponed as the custom feature + renderer would fix it anyways?

**Comment by prushforth** [comment]
I guess it depends on how big a fix it is. I would *like* to include it in the upcoming Geoserver release, but that's not a big deal. So if it's a quick fix, do it ,otherwise happy to wait for the feature renderer edition 😎
