### ISSUE TITLE
Is the web-map version of mapml-viewer up to date?

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#351]
I see in [this](http://geo.rerum.io/geolocate/mapML-view.html) map that the old Leaflet markers are still showing up, despite that it is using the latest version of mapml-viewer from there (I updated it to 2021-03-12). 

The odd thing about the markup for that map is it uses <mapml-viewer **is="web-map**> so I was thinking it might be because the web-map hadn't been updated tbd.

**Comment by ahmadayubi** [comment]
It in fact isn't using the latest version of mapml. As shown in the pictures below:
Old (used on rum geolocator):
![old](https://user-images.githubusercontent.com/55214462/111158343-4ecebb00-856e-11eb-8b0f-3a075049c7be.PNG)

New:
![new](https://user-images.githubusercontent.com/55214462/111158449-6a39c600-856e-11eb-9791-d4e4b6189480.PNG)

**Comment by prushforth** [comment]
Sure enough, I screwed up that deploy, somehow.  Fixed.
