### ISSUE TITLE
Small crisis: the summary/details marker has disappeared in the layer control in all browsers

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#358]
![image](https://user-images.githubusercontent.com/2437285/111560526-0a5b3f00-8769-11eb-8698-e7b8cecf35ae.png)

The details can still be exposed by clicking on where the triangle should be.   Would be ideal to fix this so I can rush it into the GeoServer 2.19.0 release if I can get it in there in time.

**Comment by Malvoz** [comment]
Changing the `display` of `<summary>` (https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/312) removes the native marker icons, I wonder why I didn't catch that in that PR. I can work on a quick fix if you want, but the alignment probably wont be as pretty.

**Comment by prushforth** [comment]
Ok thanks. It's not really a crisis, I can always ask for a backport for the next release in June

**Comment by Malvoz** [comment]
> I wonder why I didn't catch that in that PR, or why the screenshot does not reflect that

Chrome landed this "[feature](https://www.chromestatus.com/feature/6730096436051968)" (removing markers through changing `display` 🙄) in v89 which was released a week ago.

**Comment by ahmadayubi** [comment]
Would adding our own custom ► button work?

**Comment by prushforth** [comment]
> Would adding our own custom ► button work?

I don't think it's necessary because the triangle is pretty much a web standard for summary/details.  The issue doesn't arise because of something we did, but because of a change to the default [display](https://chromestatus.com/feature/6730096436051968) property in chrome. I'm not sure why I didn't notice that in Firefox earlier, since it appears that they had done the change a bit sooner than chrome.
