### ISSUE TITLE
Zoom to fragment of <map-a href> else zoom to extent of linked resource

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#378]
A page can have > 1 map on it, but it would be useful to be able to capture the URL fragment and set the map center or bounds based on the parameters found there.  

Maybe it could be in the form of a script that is distributed with the custom elements set, that you could configure easily to "do something" with a page's URL fragment if doing something is possible i.e. the fragment parses as something recognizable as a zoom,lon,lat or bbox etc.

**Comment by Malvoz** [comment]
A few notes:

This is essentially [Text Fragments](https://wicg.github.io/scroll-to-text-fragment/), but for maps. Something similar has been proposed for videos (linking to a particular time in a particular video on a web page) but I don't think I need to reference that from here.

Related UCR sections:
- Use Case "[Bookmark a location](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-case-bookmark)"
- Capability "[Save the location or export to other application](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#capability-export-location)"

Related MapML section: https://maps4html.org/MapML/spec/#fragments

Also, hopefully this shouldn't hijack the back button 😄

**Comment by Malvoz** [comment]
> Something similar has been proposed for videos (linking to a particular time in a particular video on a web page)

I was surprised to learn that the [Media Fragments URI](https://www.w3.org/TR/media-frags/) spec actually is [supported](https://caniuse.com/media-fragments) for video file URLs (although not embedded into pages) in most browsers.

If you visit this URL: https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm#t=2,4 the videos should start playing at 2 seconds and stop playing at 4 seconds.

Perhaps one or both these related specs can serve as guidance, e.g. for fragment syntax.

**Comment by prushforth** [comment]
Thanks, I do think these will help us think about what is possible. The bare video URL must work like a bare image/* URL, where the browser *knows* the video is the only one on the page, so its able to honour the fragment.
