### ISSUE TITLE
Allow Ctrl-Arrow decrease the pan increment

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#388]
Make it easier to target smaller features using keyboard + graticule

**Comment by Malvoz** [comment]
2 observations:
- I've been looking into gestures and keyboard controls recently, and it seems none of the UCR reference tools use the <kbd>ctrl</kbd> modifier key for anything, for some reason. So if pursuing this it might be worth investigating if that may be an issue.
- AFAICT with [Feature Indexing](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/397) this would potentially not be necessary.

**Comment by ben-lu-uw** [comment]
In the _onKeyDown function in Leaflet they return if the control key is pressed, not really sure why though. 
![image](https://user-images.githubusercontent.com/69722289/143497306-7f79a487-dd3c-4f22-97c2-e83ec096b3f8.png)
Maybe cause Chrome has a [ctrl + arrow shortcut](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-and-window-shortcuts) set for moving tabs but it does not seem to work or do anything for me? 

I did try adding this feature here https://github.com/ben-lu-uw/Web-Map-Custom-Element/tree/ctrl_pan and it seems to be issue free for me

**Comment by Malvoz** [comment]
Google Maps uses the <kbd>shift</kbd> modifier to decrease the pan increment, however Leaflet already uses that to increase it...

**Comment by prushforth** [comment]
I tested powerpoint just now and ctrl-arrow doesn't appear to do anything different than just arrow by itself.
Shift-arrow increases the size of an object, and ctrl-shift-arrow also increases the size but reduces the size increment step.

Ctrl-scrollwheel or Ctrl-+/- changes the magnification of a domain in chrome.

Ctrl-arrow skips a word in most text editors, so increases the increment of cursor movement.

Let's dig a little more to see if there's anything arguing against using ctrl-arrow for decreased pan increments.

**Comment by Malvoz** [comment]
[Ability to rotate map](https://github.com/Maps4HTML/Web-Map-Custom-Element/projects/2#card-43799698) will need a modifier too.

**Comment by ben-lu-uw** [comment]
ctrl + alt + arrow keys is what I am used to for changing orientation usually.

**Comment by ben-lu-uw** [comment]
> Let's dig a little more to see if there's anything arguing against using ctrl-arrow for decreased pan increments.

https://github.com/Leaflet/Leaflet/issues/2368
