### ISSUE TITLE
Add map control to simulate hyperlink URL destination output in lower left of map

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#392]
Browsers implement a similar control when you hover over a link, they display the destination of the link in a control in the lower left of the browser viewport.  Programs don't appear to have access to that, so we can't write to it, but we could simulate that control with a text display of the URL of a map link in the lower left of the map viewport.

**Comment by ahmadayubi** [comment]
Couldn't you also display the URL at the bottom of the browser viewport?
