### ISSUE TITLE
Point generated when no / null geometry in feature returned by query is not near click / touch location

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#409]
The handler should generate a point at the click location. It generates a point, but it seems to be far from the click location.

**Comment by ahmadayubi** [comment]
I created a example that has a query response with no geometry using CBMTILE, it seems to work as expected.

https://user-images.githubusercontent.com/55214462/115072774-d8eba580-9ec5-11eb-994b-51328b10e6ff.mp4

Would it be possible to get example mapml that recreates the issue?

**Comment by prushforth** [comment]
What projection? Try OSMTILE?

**Comment by ahmadayubi** [comment]
https://user-images.githubusercontent.com/55214462/115075010-7051f800-9ec8-11eb-9d4d-ecd68cf4e2f4.mp4

OSMTILE seems to work also, from what I can tell.

**Comment by prushforth** [comment]
Likely a GeoServer GetFeatureInfo issue, since the `<meta name="projection" />` has no content attribute:

```
<mapml xmlns="http://www.w3.org/1999/xhtml/">
   <head xmlns:html="http://www.w3.org/1999/xhtml/">
      <title>GetFeatureInfo Results</title>
      <base href="http://localhost:8081/geoserver/mapml/" />
      <meta charset="UTF-8" />
      <meta content="text/mapml" http-equiv="Content-Type" />
      <meta name="projection" />
      <meta name="cs" content="pcrs" />
   </head>
   <body xmlns:html="http://www.w3.org/1999/xhtml/">
      <feature id="" class="Arc_Sample">
         <featurecaption>precip30min</featurecaption>
         <properties>
            <table>
               <thead>
                  <tr>
                     <th role="columnheader" scope="col">Property name</th>
                     <th role="columnheader" scope="col">Property value</th>
                  </tr>
               </thead>
               <tbody>
                  <tr>
                     <th scope="row">precip30min</th>
                     <td itemprop="precip30min">4387.0</td>
                  </tr>
               </tbody>
            </table>
         </properties>
      </feature>
   </body>
</mapml>

```

**Comment by prushforth** [comment]
I believe this may be due to the fact that the event click location is, in the case of a null/ non-existent geometry, inserted into the returned feature as a point, which might be ok, but the coordinates are in lat,lng whereas usually (always, from geoserver) the document cs is pcrs.  So if the specific geometry that you insert was tagged with cs="gcrs", this might work, depending on if the renderer respects that attribute. Otherwise, I'm curious to hear how you recommend to solve this.

**Comment by prushforth** [comment]
I tested if adding `<geometry cs="gcrs">` has an effect, and sure enough the marker shows up the click location, but it causes a secondary problem with other geometries in the response, which no longer appear highlighted when focused.  I think it may reveal that the renderer isn't falling back to the `<meta name="cs" content="pcrs"/>` in the head.

```html
<mapml xmlns="http://www.w3.org/1999/xhtml/">
    <head xmlns:html="http://www.w3.org/1999/xhtml/">
        <title>GetFeatureInfo Results</title>
        <base href="http://172.17.102.189:8080/geoserver/mapml/" />
        <meta charset="UTF-8" />
        <meta content="text/mapml" http-equiv="Content-Type" />
        <meta name="projection" content="OSMTILE" />
        <meta name="cs" content="pcrs" />
    </head>
    <body xmlns:html="http://www.w3.org/1999/xhtml/">
        <feature id="" class="sfdem">
            <featurecaption>GRAY_INDEX</featurecaption>
            <properties>
                <table>
                    <thead>
                        <tr>
                            <th role="columnheader" scope="col">Property name</th>
                            <th role="columnheader" scope="col">Property value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">GRAY_INDEX</th>
                            <td itemprop="GRAY_INDEX">1225.0</td>
                        </tr>
                    </tbody>
                </table>
            </properties>
        </feature>
        <feature id="roads.636" class="roads">
            <featurecaption>light-duty road, improved surface</featurecaption>
            <geometry>
                <multilinestring>
                    <coordinates>-1.154490971022858E7 5534609.92957085 -1.154492934895731E7 5534598.84147885 -1.154498217955166E7 5534604.13929335 -1.154514578591708E7 5534620.04569973 -1.154586080596162E7 5534616.16863637</coordinates>
                </multilinestring>
            </geometry>
            <properties>
                <table>
                    <thead>
                        <tr>
                            <th role="columnheader" scope="col">Property name</th>
                            <th role="columnheader" scope="col">Property value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">cat</th>
                            <td itemprop="cat">4</td>
                        </tr>
                        <tr>
                            <th scope="row">label</th>
                            <td itemprop="label">light-duty road, improved surface</td>
                        </tr>
                    </tbody>
                </table>
            </properties>
        </feature>
    </body>
</mapml>

```

**Comment by ahmadayubi** [comment]
I think you may have found the issue. When it's synthesizing a geometry in the case where it doesn't have one, the coordinates it uses are gcrs, but if you have a `meta cs=pcrs` it considers the longitude and latitude point as a pcrs point. If you set the `meta cs=gcrs` and add a cs="pcrs" to the second feature it should work as expected. A fix would be to simply add cs="gcrs" to the synthesized geometry.

**Comment by prushforth** [comment]
> A fix would be to simply add cs="gcrs" to the synthesized geometry.

That's a good fix, but the second geometry in the file is in pcrs and it doesn't show up.  I think we [established](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/148) that the default cs  for features would be pcrs, so I believe the second feature should show up. I could add cs=pcrs to every geometry emitted by GeoServer, but that is a server-side fix and doesn't help with what "should" happen if a client leaves off the attribute.

**Comment by ahmadayubi** [comment]
It showed up for me but it was just a very small feature, I had to zoom in to see it, it's hard to tell what the expected feature is supposed to look like in PCRS coordinates though.

**Comment by ahmadayubi** [comment]
It seems the default cs changes when you click next feature for paginated queries. So the first feature has pcrs as the fallback cs but the 2nd one goes to gcrs for some reason.
