### ISSUE TITLE
zoomin links are prevented from operating

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#419]
I *think* this is a bug, but would appreciate comments. @ahmadayubi 

I created an example [page](https://maps4html.org/experiments/change-projection/zoomin-zoomout/mapml-viewer/), so that we can track requirements fulfillment, as discussed. 

Steps to reproduce:

1. Load [page](https://maps4html.org/experiments/change-projection/zoomin-zoomout/mapml-viewer/)
2. Zoom in one level, page should change projections to OSMTILE, per the markup
3. Zoom out three levels  (at level 6), projection / source change to Atlas of Canada, which should allow to zoom in, but does not

**Comment by ahmadayubi** [comment]
I believe it's because the projection only has 6 zoom levels so you can't `zoomin` more as the change in projection takes place at zoom level 7. In the other examples, the zoom level that the projection change takes place in are always within range of the projection zoom levels.

**Comment by prushforth** [comment]
Doh!
