### ISSUE TITLE
Popups are misplaced when using a screen reader

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#423]
I'm getting a strange bug where the popup is misplaced when opening it by pressing <kbd>Enter</kbd>,  _only_ when using a screen reader (NVDA in this case):

<table><td width="400"><video src="https://user-images.githubusercontent.com/26493779/106805628-3c0bc100-6667-11eb-947e-585c9f68525a.mp4"></video></td></table>

_Originally posted by @Malvoz in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/270#issuecomment-772808780_

**Comment by Malvoz** [comment]
The video is a bit out of date and popups look a bit different now, but the bug is the same.

After a popup has been opened in a [Leaflet map](https://leafletjs.com/examples/quick-start/example.html) (Leaflet markers aren't yet keyboard accessible using a screen reader, requires setting `role="button"`) the popups are not misplaced, so this seems to be a bug only in this custom element.

**Comment by prushforth** [comment]
I am certain that this is a regression, as I did listen to this map when we first published it.  But I confirm the bug. :-(

**Comment by prushforth** [comment]
OK I can't confirm that it's a regression; perhaps I'm misremembering. In any case, [this event handler](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/8f52b2bdf95fca59eca3943b1dea5a9cdbabd375/src/mapml/features/featureGroup.js#L38) correctly executes when NVDA is not running, but it doesn't execute when NVDA is running; a Leaflet handler deals with the event.  As a result the, the popup opens with its pointer at approximately 0,0 in the upper left hand corner of the map, which may be the popup div location or the map div location, who knows.

**Comment by prushforth** [comment]
Also notice that when NVDA is not running, the event is listed as a keyboard event, whereas when NVDA is running, the event is "click".  In the latter case, the popup opens in the default location for the map (0,0), upper left.

**Comment by prushforth** [comment]
I discovered / re-discovered that there are two modes for NVDA: browse mode, for reading documents, and focus mode, I think for things like forms.  I believe this bug appears in browse mode and disappears in focus mode (you can switch between the two modes with Ins+Spacebar - I couldn't figure out the indicator to tell you what mode you're in, but if you can read a page by cursoring through it, I think that means you're in browse mode).

@Malvoz Is there a way to force a map via markup to be in 'focus mode', or is that stupid?

**Comment by Malvoz** [comment]
> Is there a way to force a map via markup to be in 'focus mode'

Yes there is one way, that is https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/274.

I should've cross-referenced that issue from here, that might've saved you some time. Sorry about that!

**Comment by prushforth** [comment]
> I should've cross-referenced that issue from here, that might've saved you some time. Sorry about that!

No worries, sometimes I have to experience it to learn it!

**Comment by Malvoz** [comment]
Closed by https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/467.
