### ISSUE TITLE
Remove usage of `projection` & `zoom` parameters in `<meta http-equiv>`

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#436]
Per https://github.com/Maps4HTML/MapML/pull/171#discussion_r622254869. They can be found here: https://github.com/Maps4HTML/Web-Map-Custom-Element/search?q=http-equiv.

**Comment by Malvoz** [comment]
Is the `zoom` parameter useful?

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/c9b0d3b3f526fdfc343ad8e0e78d56184f021d3a/test/e2e/data/tiles/cbmt/alabama_feature.mapml#L4

**Comment by prushforth** [comment]
> Is the zoom parameter useful?

I don't think so. Like other media type parameters, should be used very sparingly imho

**Comment by Malvoz** [comment]
Well either they're useful (to any degree) and should be defined in the spec, or they're not useful and should not be defined nor used.

**Comment by prushforth** [comment]
Yeah I don't find them useful more the opposite since if you were going to use them the precedence of where you look for them would have to be defined. We don't look for them in the media type às far as I can recall.
