### ISSUE TITLE
Would it be useful to allow and enable more than one `<extent units="...">` per layer

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#439]
One advantage _might_ be that you could put several different projections in a single layer / mapml file and the client could pick the one that suits the map at the time.  

Another possibility is that it could provide a scope for link templates and template variable names, which might help decrease error rates when editing them by hand / copying pasting+modifying (a standard coding method!).

Idea / question for discussion, pros and cons and so on.

**Comment by prushforth** [comment]
Maybe the layer control could designate one summary/details per `<extent>`, so that you could turn on/off, and control the opacity of contents.  Just a thought, there might be complications.

**Comment by ahmadayubi** [comment]
I think the suggestion to have a separate summary for the different `<link ref=",,,">` elements was made in the past too.

**Comment by prushforth** [comment]
We should have [a way to label an extent](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263#issuecomment-934625438), which is clear for authors and implementers.  

I suggest adding a `label` attribute to the `extent` element. If absent, the value would be inherited from the parent `layer`.

**Comment by Malvoz** [comment]
>  suggest adding a `label` attribute to the `extent` element.

Sounds reasonable.

> If absent, the value would be inherited from the parent `layer`.

Not being able to differentiate between them seems problematic, there's a related issue in terms of what to do when a name/label hasn't been provided: https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/319.

**Comment by prushforth** [comment]
@Malvoz a multiple-extent layer could provide access to the individual extents' settings via the settings button [you proposed](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263#issuecomment-805854911).  Each child extent could be considered an individual "setting" of the parent, each with its own settings button that exposes the same settings structure below / inside it, (except there would be no more levels of settings - settings buttons, that is) , just the settings controls themselves i.e. opacity slider, check input, remove button, etc. (those could each be inside a details/summary, as you've shown). WDYT?

cc @Anshpreet8

**Comment by Malvoz** [comment]
Yes I think that'd form a logical structure.

> those could each be inside a details/summary, as you've shown

I only kept `details` because that's what's currently used, I'm not completely sold on the idea that each setting (opacity/style/time) should in fact be wrapped in a `details` element.
