### ISSUE TITLE
Chrome deprecation warning in console over ::-webkit-details-marker

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#455]
I wonder if it's safe to remove this now, Robert?

**Comment by Malvoz** [comment]
It is used as a fallback for browser that support it but does not support `::marker`. OTOH `::marker` is quite well [supported](https://caniuse.com/css-marker-pseudo) and we won't need either of them in the [proposed layer item anatomy](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263#issuecomment-805854911). I'm fine with removing it.
