### ISSUE TITLE
Escape key does not dismiss popup in Firefox

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#465]
... but it does in Chrome.  

Possibly related to one of [these](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/247#popups), or a regression/omission perhaps.

**Comment by Malvoz** [comment]
Yes that'd be this item:

> - [x] When focus is inside of a popup, pressing <kbd>Esc</kbd> should close the popup. Fixed in #292.

I must've only tested in Chrome...
