### ISSUE TITLE
Focus is not delegated after opening context menu in Chrome

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#469]
Pressing <kbd>Shift</kbd> + <kbd>F10</kbd> to open the context menu does not send focus to the context menu (or first menu item within) in Chrome.

**Comment by ben-lu-uw** [comment]
https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/4c452ef9879d636e843cd3174ce3bfde4695fc95/src/mapml/handlers/ContextMenu.js#L436
event.button is 0 in Firefox as expected when pressing shift + F10 but -1 in Chrome. I am unsure as to why they are different. 
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

**Comment by prushforth** [comment]
This issue didn't automatically close by merging the PR, so closing manually.  I know there's a way to make that happen.  Maybe with "Close #469" or something like that.

**Comment by Malvoz** [comment]
> This issue didn't automatically close by merging the PR

> Maybe with "Close #469"

Indeed, the syntax is `KEYWORD #ISSUE-NUMBER`, keywords are listed here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
