### ISSUE TITLE
Geogratis: Is it possible to separate HTML and MapML URLs?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#474]
In many places there are links to geogratis.gc.ca for example map viewers, such as here: https://maps4html.org/#demos.

These URLs have map viewers with the same URLs in the layer source, e.g.:

https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/ has:

```html
<map ...>
  <layer- ... src="https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/">
</map>
```

This makes it impossible for users to inspect, evaluate, understand, and give feedback on MapML (assuming it is MapML).

Is it possible to have separate URLs for the HTML documents and MapML documents on geogratis?

**Comment by prushforth** [comment]
On Geogratis if you append a url query parameter `alt=XML` to the url, you should get back the XML encoded version of the resource.

**Comment by prushforth** [comment]
e.g. https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/?alt=xml

**Comment by Malvoz** [comment]
That's neat Peter, although not obvious. Could the layer sources in the code examples have `?alt=xml` appended to them?

**Comment by Malvoz** [comment]
Side note: The `?alt=xml` file versions are served with a content-type of `application/xml;charset=UTF-8` although they're in the HTML namespace, is it problematic to change it to `text/mapml;charset=UTF-8`? Are there web platform compatibility considerations in doing so?

**Comment by prushforth** [comment]
They're served like that because browsers recognize the application/xml MIME type and parse it and format it for reading. If it gets served as text/mapml to the browser it won't be formatted and just displays as an unreadable blob of text.  

In the preview page there is always a link to the alt=xml version of the top layer of the map, just underneath the map itself.

**Comment by Malvoz** [comment]
Hopefully others are able to find that link, I keep forgetting about it. Closing, thanks.
