### ISSUE TITLE
Right clicks shouldn't activate `map-a` links

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#477]
Go to https://maps4html.org/experiments/custom-projections/Arctic-SDI/ for example, and right click (on any country I guess) to open the context menu. The link is activated and the context menu closes.

**Comment by prushforth** [comment]
I confirm this.  I think the behaviour should be a link context menu, similar  to the default for links in HTML, perhaps with a map-specific  option or two. Unsure at this moment what those might be :-).

**Comment by Malvoz** [comment]
> I think the behaviour should be a link context menu, similar to the default for links in HTML

Context menu options for standard links include "Open link in new tab", "Open link in new window", "Save links as...", "Copy link address", etc., most of which I think isn't possible/useful in a polyfill.

And because linked features can cover the entire map view in some cases it can be hard to open the general context menu for the map, so if we were to add context menu options specific to links I think a better user experience could be provided if those options were added/merged into the general map context menu instead (with a separator between these and the general map options).

Should we separate the concerns of this bug (not being able to open the context menu with right clicks) and adding context menu options specific to links, by opening a new issue for the latter?
