### ISSUE TITLE
`projection` should default to `OSMTILE`

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#481]
According to the spec, the default projection is `OSMTILE`, as such the following should work:

```html
<mapml-viewer zoom="2" lat="45" lon="-90">
  <layer- src="https://geogratis.gc.ca/mapml/en/osmtile/osm/" checked></layer->
</mapml-viewer>
```

**Comment by prushforth** [comment]
Used to work, I must have deleted that code at some point.  I'll open a PR and push some commits there as time permits; hoping to develop test coverage so that this doesn't happen again.
