### ISSUE TITLE
Time `<select>` issues

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#491]
The issues can be seen/reproduced in [debug/select-test.html](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/master/debug/select-test.html) or https://maps4html.org/experiments/datacube/

1. Can't change options in `<select>` using a mouse pointer
2. `<label>` within `<summary>` eats the pointer events so it's hard to toggle `<details>` to view `<select>` (must press the tiny "disclosure triangle")
3. HTML anatomy not consistent with opacity / style controls:<br><br>
    ```html
    <details class="mapml-control-layers"> <!-- opacity -->
      ...
    </details>
    <details class="mapml-control-layers"> <!-- style -->
      ...
    </details>
    <fieldset> <!-- time -->
      <details class="mapml-control-layers">
        ...
      </details>
    </fieldset>
    ```

**Comment by prushforth** [comment]
Would you say this is a result of #263, in general?

**Comment by Malvoz** [comment]
> 1. Can't change options in `<select>` using a mouse pointer

This is a result of only expecting `<input>` controls when implementing drag and drop of layers.

> 2. `<label>` within `<summary>` [...]

Is generally problematic and should indeed be fixed per https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263.

> 3. HTML anatomy not consistent with opacity / style controls

A design choice really, but the "extra" `<fieldset>` I think is unnecessary and its semantics are not exposed to ATs unless the element is properly labelled anyway (e.g. using `<legend>` or `aria-label(ledby)=""`).
