### ISSUE TITLE
Leaflet `marker-` assets not included in build.

### ISSUE THREAD

**Issue by erictheise** [Maps4HTML/Web-Map-Custom-Element#501]
I'm chasing down some 404 errors as I work with the new unpkg distribution.

Is there a reason that the `Gruntfile` explicitly grabs only the `layers` images?

```
src: ['layers.png','layers-2x.png'],
```

**Comment by Malvoz** [comment]
The reasoning is that Leaflet markers aren't used anymore, see https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/334. Preferably they shouldn't be fetched in that case...

**Comment by erictheise** [comment]
`leaflet.css` still tries to fetch them though.

**Comment by Malvoz** [comment]
Well, there are issues with using Leaflet as is. For example:
- We're inheriting [quite a few accessibility issues](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/247). And I don't expect them (for reasons) to be accepting PRs to fix them any time soon.
- I'd like to prefix all selectors in leaflet.css (and mapml.css) with [`:host`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host) (this has lower specificity than author provided styles, so would help with giving this component a "native feel" to it, but also allow authors to write styles without `!important` statements).

But forking Leaflet hasn't been discussed much. Maybe it's time to, @prushforth?

I'm okay with adding back the markers in the grunt file for now though.

**Comment by prushforth** [comment]
Yeah, let's put those back in for now.
