### ISSUE TITLE
Make the E2E tests run faster by launching the browser only once, at the beginning of the testing

### ISSUE THREAD

**Issue by Anshpreet8** [Maps4HTML/Web-Map-Custom-Element#518]

**Comment by ahmadayubi** [comment]
https://github.com/playwright-community/playwright-jest-examples/tree/master/basic

This example accomplishes this well for reference

**Comment by Anshpreet8** [comment]
There is a globalSetup/globalTeardown configuration in playwright that allows you to run something once before/after the execution of all the tests:
https://playwright.dev/docs/test-advanced/#global-setup-and-teardown

**Comment by prushforth** [comment]
@ahmadayubi can you advise?  I think we've hit a wall and if you've tried any of these paths before maybe you have some insight you could share.  Thanks!

**Comment by Anshpreet8** [comment]
@ahmadayubi I've tried what you've referenced above, instead of explicitly calling browser.launch(), I configured it in the jest-playwright-config.js and folder and I've also tried configuring a global setup file, but none of them appear to be working

**Comment by ahmadayubi** [comment]
Sorry I just saw this, I'll try to see if I can get the configuration working. I don't believe this issue is that trivial.

**Comment by Anshpreet8** [comment]
> believe



> Sorry I just saw this, I'll try to see if I can get the configuration working. I don't believe this issue is that trivial.

No worries, just for reference, I've pushed whatever I had into my branch (fasterTests)

**Comment by ahmadayubi** [comment]
I think the main issue is that you need to:

- remove the for loops from the test files (the preset takes care of the browser), 
- and remove any references to browserType (maybe you could find how to detect which browser it's running in, might be a method the preset provides). 
- Also you don't need to comment out the entire beforeEach function, you can keep the `await page.goto(...);` there instead of moving copying it to each of the individual tests.

Consider the following as a reference of how to configure all tests:
```js
jest.setTimeout(30000);
browserType = "Chrome"
describe("UI Drag&Drop Test in " + browserType, () => {
  beforeEach(async () => {
    await page.goto(PATH + "axisInferring.html");
  });

  test("[" + browserType + "]" + " TileMatrix inferring", async () => {
    const layerExtent = await page.$eval(
      "body > map > layer-:nth-child(1)",
      (layer) => layer.extent
    );

    expect(layerExtent.topLeft.tilematrix[0]).toEqual({ horizontal: 0, vertical: 1 });
    expect(layerExtent.bottomRight.tilematrix[0]).toEqual({ horizontal: 4, vertical: 5 });
  });

  test("[" + browserType + "]" + " TCRS inferring", async () => {
    const layerExtent = await page.$eval(
      "body > map > layer-:nth-child(2)",
      (layer) => layer.extent
    );

    expect(layerExtent.topLeft.tcrs[0]).toEqual({ horizontal: 0, vertical: 256 });
    expect(layerExtent.bottomRight.tcrs[0]).toEqual({ horizontal: 256, vertical: 512 });
  });

  test("[" + browserType + "]" + " PCRS inferring", async () => {
    const layerExtent = await page.$eval(
      "body > map > layer-:nth-child(3)",
      (layer) => layer.extent
    );
    expect(layerExtent.topLeft.pcrs).toEqual({ horizontal: 100, vertical: 600 });
    expect(layerExtent.bottomRight.pcrs).toEqual({ horizontal: 500, vertical: 150 });
  });

  test("[" + browserType + "]" + " GCRS inferring", async () => {
    const layerExtent = await page.$eval(
      "body > map > layer-:nth-child(4)",
      (layer) => layer.extent
    );
    expect(layerExtent.topLeft.gcrs).toEqual({ horizontal: -92, vertical: 52.999999999993484 });
    expect(layerExtent.bottomRight.gcrs).toEqual({ horizontal: -62, vertical: 33.99999999999964 });
  });
});
```

This should work, it's the axisInferring.test.js file, just a reminder to test individual files, you can use `npm t axisInferring` and it'll just run that test

For you're branch revert the changes made to jest.config.js and update jest-playwright.config.js to:
```js
module.exports = {
    server: {
        command: 'node test/server.js',
        port: 30001,
        launchTimeout: 10000,
    },
    browsers: ["chromium"],
    exitOnPageError: false, // GitHub currently throws errors
    launchOptions: {
        headless: true
    }
}
```

**Comment by ahmadayubi** [comment]
Removing `--detectOpenHandles` will allow running test in parallel, this may require some changes to tests but has potential speed benefits.

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/a086e23baaab557179b7a66ceb5ce2ae769f4f83/package.json#L34
