### ISSUE TITLE
Add M.options for setting default options

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/Web-Map-Custom-Element#526]
The M.options parameter will set defaults that will be used to control user preferences, the state of these preferences can be maintained through the [mapml-viewer extension](https://github.com/Maps4HTML/mapml-extension).

**Comment by prushforth** [comment]
So the _reloadUI() would be called by the extension to notify the mapml-viewer of preference changes made by the user? I don't understand why you would need to rebuild the entire map, tbh (not clear to me at least).

Maybe a more meaningful method name, such as reloadPreferences or something like that.

The window.M belongs to the mapml-viewer. Is it the right way to communicate between the extension and the viewer?  Maybe, seems reasonable, but maybe there's existing examples to follow somewhere?
