### ISSUE TITLE
Context menu "Toggle Controls" does not work when map starts with no controls

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#545]
I **think** the bug is as described in the title of this issue.  Try toggling controls in[ this example](https://maps4html.org/experiments/screenreader/restaurants/), compared with [this one](https://maps4html.org/experiments/styling/alternate-styles/).

**Comment by AliyanH** [comment]
The "Toggle Controls" context menu item is now disabled when a map is started with no controls. See more here - https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/696
