### ISSUE TITLE
Clicking +/- keys still fires moveend event when zoom in/out is disabled

### ISSUE THREAD

**Issue by ben-lu-uw** [Maps4HTML/Web-Map-Custom-Element#550]
. . . unlike the on screen buttons and the scroll wheel

**Comment by prushforth** [comment]
I am having difficulty reproducing this issue.  What branch should I be looking at to listen to the bug, perhaps [this one](https://github.com/ben-lu-uw/Web-Map-Custom-Element/tree/announce_zoom_and_move)?  So, if I listen to the [painting](https://maps4html.org/experiments/painting/) with the unfixed branch, should I experience this issue?

To solve the issue I think I should merge [this branch](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/567) into the head of the above?  Is that correct?

**Comment by ben-lu-uw** [comment]
This happens on any branch. If you console log here you should be able to see that moveend is being called. 
https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/a086e23baaab557179b7a66ceb5ce2ae769f4f83/src/mapml-viewer.js#L443-L449

**Comment by prushforth** [comment]
@ben-lu-uw can this be merged?

**Comment by Malvoz** [comment]
Fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/567.

(it's the keyword syntax thing, mentioned in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/469#issuecomment-930502685 😋)
