### ISSUE TITLE
Vector rendering issue

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#559]
In [this page](https://maps4html.org/experiments/vector-tiles/mapml/mapml-viewer/), there are two maps. The bottom map is Web Mercator / OSMTILE.  There's a [feature](https://github.com/Maps4HTML/experiments/blob/dc71d8e97420f3f3a0fd12d93de5793bf576388b/vector-tiles/mapml/tiles/osmtile/2/1/1.mapml#L213) (El Salvador id="fclass.73") that renders with an apparent point marker.    

![image](https://user-images.githubusercontent.com/2437285/140090438-3715b551-d3c1-4c6b-b7a2-ab5ceb062279.png)

 @ahmadayubi can you take a look please.

**Comment by jerstlouis** [comment]
@prushforth That is exactly the rendering bug I saw and was describing, with the strokes as opposed to the fill. However for some reason when I tried it again I could not reproduce it?

**Comment by prushforth** [comment]
Doesn't show up when I change the source to your service now, so that's good.  Still curious if its a bug.

**Comment by jerstlouis** [comment]
@prushforth It happens in the bottom pane with the wrapping around world, but not in the top pane.

**Comment by prushforth** [comment]
The top pane is WGS84 (your WorldCRS84Quad) and the bottom pane is OSMTILE (your WebMercatorQuad), so different sources from my point of view.  Also, copied from your service at widely separated times.  As I mentioned, I don't see a replication of the rendering artifact mentioned here when I point the tile template at your WebMercatorQuad service today.

**Comment by prushforth** [comment]
With this input:

```
<map-feature id="fclass.73" class="fclass">
         <map-geometry>
            <map-polygon>
               <map-coordinates>-10019154.93269 1538354.08306 -10018754.17139 1538179.92761 -9953778.73157 1518203.74208 -9871068.81875 1482220.46653 -9790805.04014 1478766.01397 -9768484.06551 1498870.65375 -9796003.07532 1547622.63538 -9951944.13091 1647924.2825 -10018754.17139 1569038.46245 <map-span class='noline'>-10019154.93269 1569012.97177 -10019154.93269 1538354.08306</map-span></map-coordinates>
            </map-polygon>
         </map-geometry>
...
</map-feature>
```
we get this output:

```
<g aria-label="Feature" data-fid="fclass.73">
    <path class="fclass" stroke="none" fill="#3388ff" fill-opacity="0.2" fill-rule="evenodd" d="M0 217L0 217L2 217L4 218L6 218L6 218L6 216L2 214L0 216L0 216L0 217z" style="stroke: none;"></path>
    <path class="fclass mapml-feature-outline" stroke="#3388ff" stroke-opacity="1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none" d="M0 217L0 217L0 217L2 217L4 218L6 218L6 218L6 216L2 214L0 216L0 216" style="fill: none;"></path>
    <path class="noline fclass" stroke="none" fill="#3388ff" fill-opacity="0.2" fill-rule="evenodd" d="M0 216L0 217"></path>
</g>
```

We get a good rendering:
![image](https://user-images.githubusercontent.com/2437285/140166209-e2a7c87d-3639-41b8-bbe1-4c9acd1cff12.png)

With this input:

```
<map-feature id="fclass.73" class="fclass">
    <map-geometry>
        <map-polygon>
            <map-coordinates>
                -10019154.93269 1538354.08306 -10018754.17139 1538179.92761 -9953778.73157 1518203.74208 -9871068.81875 1482220.46653 -9790805.04014 1478766.01397 -9768484.06551 1498870.65375 -9796003.07532 1547622.63538 -9951944.13091 1647924.2825 -10018754.17139 1569038.46245 
                <map-span class="noline">-10019154.93269 1569012.97177 -10019154.93269 1538354.08306</map-span>
            </map-coordinates>
        </map-polygon>
    </map-geometry>
</map-feature>
```
we get this (incorrect) output:

```
<g aria-label="Feature" data-fid="fclass.73">
    <path class="fclass" stroke="none" fill="#3388ff" fill-opacity="0.2" fill-rule="evenodd" d="M0 217L0 217L2 217L4 218L6 218L6 218L6 216L2 214L0 216L0 216L0 217z" style="stroke: none;"></path>
    <path class="fclass mapml-feature-outline" stroke="#3388ff" stroke-opacity="1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none" d="M0 217 L-12.5 187 C-12.5 167, 12.5 167, 12.5 187 L0 217z" style="fill: none;"></path>
    <path class="noline fclass" stroke="none" fill="#3388ff" fill-opacity="0.2" fill-rule="evenodd" d="M0 216L0 217"></path>
</g>
```

and the incorrect rendering: 

![image](https://user-images.githubusercontent.com/2437285/140167030-a12738a1-35af-4993-aa6a-77dab56eb5e3.png)

When I normalize (remove extraneous whitespace (that I did introduce with XSLT), 

```
            <map-geometry>
                <map-polygon>
                    <map-coordinates>-10019154.93269 1538354.08306 -10018754.17139 1538179.92761 -9953778.73157 1518203.74208 -9871068.81875 1482220.46653 -9790805.04014 1478766.01397 -9768484.06551 1498870.65375 -9796003.07532 1547622.63538 -9951944.13091 1647924.2825 -10018754.17139 1569038.46245 <map-span class="noline">-10019154.93269 1569012.97177 -10019154.93269 1538354.08306</map-span></map-coordinates>
                </map-polygon>
            </map-geometry>
```

the rendering problem goes away:

![image](https://user-images.githubusercontent.com/2437285/140170316-1702cc22-bca6-4283-862b-06ba9be73b04.png)

CASE CLOSE

**Comment by jerstlouis** [comment]
@prushforth Glad to see the mystery solved :) Are such white spaces at the beginning of `map-coordinates` treated as significant? This may point to the fact that they should not be. I am not sure whether that is the case in GML, would you know?

**Comment by prushforth** [comment]
I am pretty certain that whitespace is not significant, and should be normalized before parsing. In this case I imagine it goes back to my own use of a regex, that was never properly tested. We'll fix that now.
