### ISSUE TITLE
Feature links should delegate focus

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#580]
Repro steps for https://maps4html.org/experiments/linking/features/:

1. <kbd>Tab</kbd> three times to focus the Prince Edward Island feature
2. Press <kbd>Enter</kbd> to visit the feature link

On step 2:
 - "Interactive map, region" is announced 
    Expectation: "Prince Edward Island" is announced
 - The Prince Edward Island feature is not focused (tabbing starts from the map component -> Newfoundland and Labrador -> Prince Edward Island)
    Expectation: Prince Edward Island is focused

Can focus be sent to features after activating feature links?

**Comment by prushforth** [comment]
> Can focus be sent to features after activating feature links?

I think so.   We'll try to fix this.

**Comment by ben-lu-uw** [comment]
When you first tab to PEI it will announce "Prince Edward Island", and in step 2 you want it to announce it again? Isn't that a bit redundant. @Malvoz

**Comment by Malvoz** [comment]
> in step 2 you want it to announce it again?

@ben-lu-uw I guess that's just the effect focus has, and is not unlike e.g:
```html
<!-- links in a table of contents -->
<a href="#cats">Cats</a> <!-- on focus: "Cats" announced -->

<!-- page content -->
<h2 id="cats">Cats</h2> <!-- on focus as a result of following the above link: "Cats" announced -->
```

Also, I'm not exactly sure how feature links work but I guess a feature can be named one thing but link to a feature with another name, in which case it makes even more sense that the feature name is announced as a result of focus.
