### ISSUE TITLE
How to caption the map / mapml-viewer

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#597]
I recall a conversation but can't find it; it may have been in gitter.  Anyway, I would like to develop a solution, or apply a best practice for providing a label/caption/title for the `<mapml-viewer>` / map element itself, so that perhaps, instead of a screen reader user hearing "Interactive map", "region" they might here "Interactive map of (Middle Earth etc)" and any other accessibility clues as to what to expect next.

Would there need to be a visual equivalent developed or provided if there already exists an accessibility solution for this.

This issue can be closed/deleted as required.

**Comment by Malvoz** [comment]
https://github.com/Maps4HTML/Web-Map-Custom-Element/discussions/558
