### ISSUE TITLE
Develop, test and document release procedure

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#602]
The objective is to have a reference document that we can follow to end up with a new version of our polyfill that is npm installable.

Our release guide should be something like how_to_release.md, should end up in the root of this repo.

The end user installation guide should end up as a .md document in the root of this project, named like INSTALLATION.md or similar, and will focus how to get to the point where:

`$ npm install @maps4html/web-map-custom-element`

 (or its successor, probably `mapml-viewer`) will do something useful for you.

[npm docs](https://docs.npmjs.com/)

[maps4html organization on npm](https://www.npmjs.com/search?q=maps4html)

**Comment by ben-lu-uw** [comment]
Version 0.9.0 published on npm 😄
