### ISSUE TITLE
Migrate from jest-playwright to Playwright test-runner

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#608]
Looks like the playwright project has their own test runner now, so we can reduce our dependencies and hopefully get past these flaky tests by migrating from [jest-playwright](https://github.com/playwright-community/jest-playwright#jest-playwright) to [playwright test-runner](https://playwright.dev/docs/intro/)

**Comment by ahmadayubi** [comment]
I wonder if they support unit tests in the runner, in the meantime I also found https://playwright.dev/docs/test-retries/#retries. Playwright allows the ability to retry failed tests, it maybe useful, if a test fails but passes on a retry it gets labelled as 'flaky'.

**Comment by prushforth** [comment]
Unit tests seem to be not supported. Will have to figure out a path forward for them.

**Comment by prushforth** [comment]
Bumping this because jest is driving me mad, and I hope that playwright test-runner will not do that :-).  For unit tests we could move to an additional test runner that specializes in that, or ditch the unit tests if we have to.  Also I think playwright may have [fixed their problem with firefox](https://github.com/microsoft/playwright/issues/10833), at least they moved that issue out of their to-do list.
