### ISSUE TITLE
Popups for static features close automatically

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#613]
Noticed that popups close automatically when they have to be panned into view:

<table><td width="300"><video src="https://user-images.githubusercontent.com/26493779/149357773-558ca0ed-d6e7-4e25-99d1-63e4c5d6a93b.mp4"></video></td><td width="500" valign="top"><video src="https://user-images.githubusercontent.com/26493779/143910471-a572c26c-2999-4102-8deb-e389d0f3161c.mp4"></video></td></table>

**Comment by prushforth** [comment]
Can no longer reproduce, closing.  If it's still a problem, re-open. Thank you.
