### ISSUE TITLE
`hreflang` - to implement or not to implement (and remove from spec/docs)

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#619]
I noticed that we specified a [`hreflang` attribute](https://maps4html.org/MapML/spec/#dom-htmllinkelement-hreflang) of `<map-link>`, which seems like a nice idea, but there is no indication that it's implemented anywhere in our code.  

Should we remove it from the spec?  I can't see it being removed from the [HTML Link Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-hreflang) anytime, but unless we start to implement internationalization in the polyfill in a more serious way, I can't see it being implemented any time soon, so maybe we should remove and add back later if necessary.

**Comment by Malvoz** [comment]
I guess this is where built-ins shine? 🤔 The attribute is <q>[purely advisory](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-hreflang)</q> and I don't think there's any way to support it in autonomous custom elements?

This issue relates to https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/485.

**Comment by prushforth** [comment]
Yes, I will simply document it as purely advisory for the moment.  I can think of applications of it where it wouldn't be purely advisory (i.e. perhaps unused/unimplemented), but that's another story.  I guess it won't hurt to leave it in as such.
