### ISSUE TITLE
Test and Implement Leaflet 1.9.x*

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#658]
Currently, there are a few issues I see when running web-map-custom-element under Leaflet 1.8.0.beta 3

- [ ] get tests running
- [ ] provide feedback to Leaflet committers
- [ ] other - please comment

I tested the experiments with 1.8.0 beta 3, and it seems to work pretty well.  I noticed a couple of things:

- layer control context menu no longer available /  replaced by browser context menu
- after following a map-a link, the mouse pointer is stuck in the dragging state until released by another event
- unable to distinguish if tests are broken because test infrastructure isn't great or if the upgraded API causes breakage.  Only a few tests (16) were broken, out of ~300.

**Comment by Malvoz** [comment]
> - [ ] provide feedback to Leaflet committers

Here: https://github.com/Leaflet/Leaflet/discussions/8044.

**Comment by Malvoz** [comment]
- [ ] For the same [reasons](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/571#issuecomment-1002313054) we decided not to go through with https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/482, it's perhaps desirable to disable Leaflet's new feature `autoPanOnFocus` which is enabled by default: https://github.com/Leaflet/Leaflet/pull/8042.

**Comment by Malvoz** [comment]
@prushforth I don't think it's too long until the release of [v1.9.0](https://github.com/Leaflet/Leaflet/milestone/38), FYI.

**Comment by Malvoz** [comment]
Leaflet [v1.9.1](https://github.com/Leaflet/Leaflet/blob/v1.9.1/CHANGELOG.md#191-2022-09-23) has been released! 🙂

Blog post: https://leafletjs.com/2022/09/21/leaflet-1.9.0.html
