### ISSUE TITLE
zoomTo fails when the zoom is the same as the current zoom

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#66]

**Comment by ahmadayubi** [comment]
Can you share steps to reproduce the bug? I tried `<map>.zoomTo(lat, lon, zoom)` with the zoom equal to the maps current zoom level, and the map still zoomed to the lat,lon.

**Comment by prushforth** [comment]
It's been a while and may not apply to this version of the code; I will try it on the old polymer version and update this issue if need be.
