### ISSUE TITLE
'us_pop_density' not displaying in maps that use it

### ISSUE THREAD

**Issue by ben-lu-uw** [Maps4HTML/Web-Map-Custom-Element#660]
Starting in commit https://github.com/Maps4HTML/Web-Map-Custom-Element/commit/b108e33535b9aad61be269a0c97db2460d28e155 (Multiple extents on the main repo), pages that use `us_pop_density.mapml` no longer seem to display it.
![image](https://user-images.githubusercontent.com/69722289/166576561-97e07132-e90e-4986-9896-41934e27005c.png)

**Comment by prushforth** [comment]
I believe this is caused by a change in the default coordinate system (went from default of 'gcrs" to default of 'pcrs'). Try adding a \<meta name="cs" content="gcrs">\</meta> to the file.

**Comment by ben-lu-uw** [comment]
Fixed in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/636/commits/c2c88e8aeaa99f03a2c4b50a3eb9666bdc0833a8
