### ISSUE TITLE
Appending a layer to layer-less map does not add layer controls 

### ISSUE THREAD

**Issue by ben-lu-uw** [Maps4HTML/Web-Map-Custom-Element#672]
... while if a layer- element was pre written in the html it would appear as normal.
![image](https://user-images.githubusercontent.com/69722289/177388893-b332d019-ec8d-4301-bc6e-a619e4d9e485.png)

**Comment by prushforth** [comment]
This is a bug; the constructor for a custom element should not create any DOM children, that work should be done in the connectedCallback.

**Comment by Malvoz** [comment]
> should a map that has no layers have a layer control?

It was decided that it should not: https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/160.

> should the layer control appear when the first layer is added and disappear when the last layer is removed.

IMO yes.
