### ISSUE TITLE
Use map projection attribute as fallback projection for a layer if the layer does not specify a projection

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#677]
A layer can have a single or a few feature(s) in it, and sometimes it would be developer-friendly to not have to specify the projection via a map-meta element, or even as is sometimes seen (MapServer?) via the text/mapml MIME type `projection` parameter.  It would be developer friendly to allow that layer to just assume that the projection is compatible with the `<mapml-viewer projection="value"...>` and try that.  If it renders, that's good, otherwise it might become a disabled (inert) layer until DOM changes occur that make it not disabled.

Edit: it might not work, but it's worth a try.

**Comment by yhy0217** [comment]
Resolved in #854

There is a remaining bug for map projection, see #899
