### ISSUE TITLE
Menu items in the context menu shouldn't wrap

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#684]
As seen in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/683#issuecomment-1213453371:

<img src="https://user-images.githubusercontent.com/2437285/184430827-d0cebed3-e28e-4e04-a413-41dd0f97cff4.png">

Ideally the menu's width would adjust to the content within.

**Comment by prushforth** [comment]
This perhaps relates to, or at least should inform how the copy paste menus are created  in #698
