### ISSUE TITLE
Source of maps tiles

### ISSUE THREAD

**Issue by tomayac** [Maps4HTML/Web-Map-Custom-Element#686]
@prushforth, we have discussed this in the past, but I still don't fully understand your vision there. The thing is: tile data is valuable information that costs a lot of money to curate and serve, and even community-funded and -sourced OSM [say so](https://operations.osmfoundation.org/policies/tiles/).

Let's say for a moment browser vendors agree to implement a map element similar to what you describe in the spec. On Chrome, it would use Google Maps tiles, on Safari, it would use Apple Maps tiles, and on Firefox, it would use OSM Maps tiles. 

Let's say you wanted to organize a party in your remote neighborhood's rural community garden and you center the map exactly on the spot. On OSM, it would be very detailed and show each garden parcel perfectly. On Apple Maps, you would see the community garden per se highlighted, but not individual garden parcels. And on Google Maps, the entire area would just be a green area without details. You would probably agree that the cross-browser experience would not be great. 

For reference, here are screenshots for said experiment:

- [OSM Maps tiles](https://drive.google.com/file/d/1NNmu_UDlEblIbJQh7-Sm1MikvwAsNkE4/view?usp=sharing)
- [Apple Maps tiles](https://drive.google.com/file/d/1ZEmFWYXOUzfbYV9m5LGKtEe1mzmqRsVn/view?usp=sharing)
- [Google Maps tiles](https://drive.google.com/file/d/1wssi7N8dXyCxwexgXMTSiRPEKRiKe561/view?usp=sharing)

The example point of interest is this [garden parcel](https://goo.gl/maps/opAs3zBytqv5dgpy5) (randomly chosen, I have no affiliation with this place).

Or am I misunderstanding the proposal entirely wrong? If so, I'm happy to be corrected.

**Comment by tomayac** [comment]
![Screenshot 2022-10-03 at 09 50 44](https://user-images.githubusercontent.com/145676/193528388-baa810a5-2073-494d-9385-4e4d45fd632d.png)
![Screenshot 2022-10-03 at 09 51 52](https://user-images.githubusercontent.com/145676/193528394-79e17e44-f876-443e-9336-7a0519dc5b92.png)
![Screenshot 2022-10-03 at 09 52 16](https://user-images.githubusercontent.com/145676/193528397-1174eca5-66ae-4d3d-bcf8-70ce4ec7c5df.png)

**Comment by prushforth** [comment]
Hi Thomas,. The source of map info is not tied to the browser, it's up to the author.  The author can use \<layer- src="any URL to MapML">\</layer-> OR inline map content that fetches tiles, images, features etc from wherever they like. There are examples on our docs pages here: https://maps4html.org/web-map-doc/ The pattern whereby content is couple to the browser is an anti-pattern, and we're specifically not contemplating that fwiw.

**Comment by tomayac** [comment]
I see. I guess the confusion stems from the fact that my assumption was that layers are _data_ layers, as in, say, restaurants (see the code sample). In my head, the underlying base map is not a "layer" like all others. 

```html
  <layer- label="CBMT" src="https://geogratis.gc.ca/mapml/en/cbmtile/cbmt/" checked></layer->
  <layer- label="Restaurants" src="demo/restaurants.mapml" checked></layer->
  <layer- label="Canada's Provinces and Territories" src="demo/canada.mapml" checked></layer->
```
