### ISSUE TITLE
Add Copy/Paste Layer options in the context menu

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/Web-Map-Custom-Element#692]
- Add a Copy Layer option in the layer context menu (Copies the `<layer->` element to clipboard):
![image](https://user-images.githubusercontent.com/55751566/198673713-014fe8ab-c3ce-4f15-8769-9c6e54dc3a30.png)

- Add a Paste Layer option in the map context menu (Access the clipboard to paste a `<layer->` element):
Add support for pasting GeoJSON, once geojson2mapml is integrated into web-map-custom-element.
![image](https://user-images.githubusercontent.com/55751566/198674081-2779868e-9d2c-40a9-8842-146abef27d4c.png)

**Comment by prushforth** [comment]
I think "Paste Layer (P)" could be simply "Paste (P)" wdyt?  At the map level I wouldn't expect anything else to happen, regardless of the format, I think.

**Comment by AliyanH** [comment]
> I think "Paste Layer (P)" could be simply "Paste (P)" wdyt? At the map level I wouldn't expect anything else to happen, regardless of the format, I think.

I agree.

> Also this is a non-trivial UI exercise, we have to disable the option if there's nothing to paste, enable when we recognize and support whatever it is.

That would be interesting, good idea!

**Comment by AliyanH** [comment]
> Also this is a non-trivial UI exercise, we have to disable the option if there's nothing to paste, enable when we recognize and support whatever it is.

@prushforth A possible issue with this method, is that whenever the user opens the context menu for the map, the browser will ask for clipboard access, even if their intention is not to paste anything into the map (as we will have to access their clipboard to check if there is anything there to paste)

**Comment by prushforth** [comment]
> we will have to access their clipboard to check if there is anything valid to paste

Interesting point. I guess we can skate over it for now; for the browser to do something similar might not involve the permission dialog (the browser could check and enable/disable the menu item without asking permission, but if the user tried to actually select the Paste item, permission would have to be obtained.  I think.)
