### ISSUE TITLE
Re-organize and re-design copy/paste menus

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#698]
Top level context menu could be re-organized like so:

![image](https://user-images.githubusercontent.com/2437285/203357719-1f57536d-645c-4318-9988-962966a2e557.png)

I think we could get rid of this menu:

![image](https://user-images.githubusercontent.com/2437285/203360149-7e98a28d-01ec-47ef-b556-b3328a0f15a6.png)

The first level submenu of Copy (C) would be something like:

![image](https://user-images.githubusercontent.com/2437285/203376736-cee9e23a-0a5f-45be-a98d-0ec0ac84e503.png)

The Map item would do what Copy MapML (M) currently does, that is, copy the html code for the current map including any updates since page load i.e., a dynamic snapshot of the DOM node for the map.

The Extent item would copy the map's **current** extent onto the clipboard using the clipboard API, as a couple of different formats:

- MapML: `<map-meta name="extent" content="top-left-easting=-8433179, top-left-northing=5689316, bottom-right-easting=-8420968, bottom-right-northing=5683139"></map-meta>` - coordinates in PCRS units by default. 
- GeoJSON: A [Feature object with a bbox member ](https://www.rfc-editor.org/rfc/rfc7946#section-5) should be generated, according to GeoJSON semantics. The coordinates would be GCRS by default:
```JSON
   {
       "type": "Feature",
       "bbox": [-75.756741, 45.39263,-75.646791,45.429000],
       "geometry": {
           "type": "Polygon",
           "coordinates": [
               [
                   [-75.756741, 45.39263],
                   [-75.646791, 45.39263],
                   [-75.646791, 45.429000],
                   [-75.756741, 45.429000],
                   [-75.756741, 45.39263]
               ]
           ]
       }
   }
```
We could add a browser extension setting to allow user to set what coordinate system they want for any copy operations/ formats.

The Layer > item would bring up a list of items with each layer in the map in it (i.e., it would be dynamically generated).  Selecting one of the layer items would have the same effect as the Copy Layer (L) layer control context menu item does today.

![image](https://user-images.githubusercontent.com/2437285/203377379-4d0b9a37-00f5-45d2-8d09-efe30fc394e5.png)

The Location item would do what Copy Coordinates currently does, except having eliminated the coordinate system submenu, we would copy the cursor location onto the clipboard in supported formats, in the coordinate system expressed by their preference (in the extension, per above).

The layer control context menu could be re-designed to have Copy and Paste items eventually, for consistency.  Let's treat that as a separate issue as there may be layer specific considerations and new functionality (e.g., Paste would be new).

The Paste menu item should allow pasting of either MapML or GeoJSON as a new layer. When the paste target is the map, a new layer on top of the map should be created.  When the paste target is a layer, which is not yet possible, but maybe it could allow pasting of features, extents and other content, either from GeoJSON or MapML into the current layer.

There's currently no "selection" abstraction in MapML, but maybe one day there could be, similar to selecting text in an HTML document interface, but let's leave that aside for now.

**Comment by prushforth** [comment]
In discussion with the team, we don't think that a Layer submenu for Copy is useful, as it duplicates the functionality from the Layer Control context menu.  

When copying a layer, the URLs should be resolved, if they're relative, so that what gets copied may be used by the person doing the copying.

**Comment by AliyanH** [comment]
linked to https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/323.
