### ISSUE TITLE
Review consistency of the `<layer- checked`> (and `<extent checked>`) attribute with `<input checked>` 

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#716]
In reviewing how our elements' design relates to the [Web Platform Design Principles](https://www.w3.org/TR/design-principles/#attribute-reuse), we're told to ensure consistency of attribute use with existing attributes of the same name.  

We should review `checked` to ensure some consistency with [the API of the `<input checked>` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#attr-checked).  That said, our use of checked is a bit different from that of `<input>`, but it does have similar UI implications.

The `checked` attribute seems to be one of the few counterpatterns that is listed that [should **not** be kept in sync with the IDL attribute (property)](https://www.w3.org/TR/design-principles/#html-idl-must-by-synced).

**Comment by yhy0217** [comment]
Resolved in #887

> The checked attribute seems to be one of the few counterpatterns that is listed that [should not be kept in sync with the IDL attribute (property)](https://www.w3.org/TR/design-principles/#html-idl-must-by-synced).

The current implementation follows the pattern, the checked attribute is kept sync with the IDL attribute.
