### ISSUE TITLE
Can't focus map with debug mode enabled at Leaflet 1.9.3

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#720]
![image](https://user-images.githubusercontent.com/2437285/214065787-cf8c3d73-bca7-4b19-95f5-c1dd70eaed61.png)

**Comment by prushforth** [comment]
I think we can close this... @kevinkim31 @AliyanH WDYT ?

**Comment by kevinkim31** [comment]
Yep. I agree

**Comment by AliyanH** [comment]
Yup, works like a charm!
