### ISSUE TITLE
Custom built in element web-map is setting host styles in the parent document, it should be in the shadow root.

### ISSUE THREAD

**Issue by Jacky0299** [Maps4HTML/Web-Map-Custom-Element#751]
_changeWidth and _changeHeight function should adapt the change. web-map element has an additional div element.

**Comment by Jacky0299** [comment]
For web-map only, the host styles are set in the <head>, as for mapml-viewer, the host styles are set in the shadowroot. Changes to the web-map should be made.

**Comment by Jacky0299** [comment]
![image](https://user-images.githubusercontent.com/83443908/222473123-67ab1b2c-519d-4ba6-a7b5-5fa3c39a3741.png)
vs.
![image](https://user-images.githubusercontent.com/83443908/222473308-a33466cf-04c1-4edb-be83-c4f3ad1b482e.png)

**Comment by prushforth** [comment]
Have a look at [:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host).  You may need to experiment with the selector that you pass to it.

**Comment by Jacky0299** [comment]
For web map, the :host in the shadowroot is selecting the rootDiv: mapml-web-map. It is not possible for it to select the parent element as we want which is the <map> element. Therefore, setting the style for the <map> element is not possible in the shadowroot of the rootDiv under <map>.
