### ISSUE TITLE
Can not check/uncheck layers using keyboard navigation

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/Web-Map-Custom-Element#752]
For ex, tabbing to layer control [here](https://maps4html.org/experiments/screenreader/restaurants/) and checking/unchecking a layer with keyboard navigation (by pressing space bar or enter on the checkbox) does not function as intended. Bug appeared after [leaflet 1.9.3 upgrade](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/715).

Similar behavior can be seen on the [leaflet site](https://leafletjs.com/examples/layers-control/) where enter does not work when checkbox is focused, but spacebar works as intended.

**Comment by prushforth** [comment]
Definitely spacebar should work, but "Enter" doesn't work on the [checkbox on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox), so I suspect that's normal.
