### ISSUE TITLE
Multiple extents tab order is messed up when extents are re-ordered

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#756]
Steps to reproduce:

Load [this page](https://maps4html.org/experiments/multiple-extents/).

Open the layer control, and expose the multiple extents of the National Geographic layer via the settings button.
Drag the extent named "National Geographic" from first position into second position.
The "X" (delete extent") for the National Geographic extent moves to be positioned on top of but slightly askew from the "X" symbol for the whole layer.
Use Tab key to change focus from layer checkbox through and past the now-second National Geographic extent. The tab order still respects the "X" symbol for the repositioned extent, despite that the "X"symbol is misplaced.

![image](https://user-images.githubusercontent.com/2437285/219458890-060c3cfd-a6bf-4813-b94c-825c2d88661b.png)

Perhaps it's just that the "X" symbol is misplaced, not that the tab order is messed up.  If you toggle the whole layer, the "X" symbols are correctly positioned and tab order seems fine.

**Comment by AliyanH** [comment]
I was not able to replicate it (tried on chrome, Edge, Firefox)

https://user-images.githubusercontent.com/55751566/219463932-2484140b-18f7-4fee-9ac2-1121be9e4f36.mp4

**Comment by prushforth** [comment]
That's weird.  I confirm that it doesn't happen on Firefox, nor on an Edge InPrivate tab (Edge won't let me use it without signing into windows, which has me not wishing to use Edge).  But it is happening in my Chrome on Windows as well as in Chrome on Linux.

**Comment by prushforth** [comment]
Can't reproduce today, closing as mystery.
