### ISSUE TITLE
Add a "Zoom to layer" function

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#77]
per suggestion from Keith Pomakis, the client should be able to zoom to the ultimate bounds/min zoom of a layer via a user interface affordance.

**Comment by pomakis** [comment]
I think the best way to accomplish this is to provide a clear way for a MapML layer to indicate its spatial extent.  (At the moment there doesn't seem to be one.)  Then the client-side "zoom to layer" operation would be nothing more than zooming (and panning) to that extent.
