### ISSUE TITLE
Copy / paste a layer doesn't respect the checked status

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#776]
Steps to reproduce

Load [this page](https://maps4html.org/experiments/api/geojson/)
Uncheck a layer
Open layer context menu for that layer
Copy Layer
Open map context menu
Paste layer
Open layer control - layer is checked, but not displayed.
Toggle layer checked state, visiblity of layer is correct now

**Comment by AliyanH** [comment]
When you pan the map you can see that it gets updated, and the layer eventually gets unchecked in the layer control:

https://user-images.githubusercontent.com/55751566/223230495-4fafe005-38da-42da-a4b1-e0649ec8178b.mp4

**Comment by prushforth** [comment]
Weird but ok!
