### ISSUE TITLE
Error when following link within layer

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#784]
Steps to reproduce:

Load [this page](https://maps4html.org/experiments/painting/)
Open console
Click on Girl link

Error is reported: 
mapml.js:6730 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at i._handleFocus (mapml.js:6730:51)
    at SVGGElement.o (leaflet-src.js:2799:15)

![image](https://user-images.githubusercontent.com/2437285/224134886-89f46068-e2b8-45e3-9139-584e531378c7.png)

**Comment by yhy0217** [comment]
Resolved (probably) in 1ac902f9ca08dc09de29e5249b6582033098e2e4 and #891
