### ISSUE TITLE
Treat `controlslist` as a positive-choice list for non-default controls

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#789]
Currently the `<mapml-viewer controlslist="nofullscreen"...>` attribute is used exclusively as a way to exclude one or more of the default controls for the map.

This issue is for discussion of the extension of the use of `controlslist` to include the ability to positively identify what non-default controls to **add** to the map. 

The idea is that you would continue to use the "no"-prefixed token to prune what default controls are added, but you could explicitly add non-default controls by referring to them without the "no" prefix, For example, if we supported a legend control, we could explictly add it to the map using `<mapml-viewer controlslist="legend">`.  This way, the HTML author can decide what controls to show based on their own requirements, but also leaving it up to the implementer as to what controls to support.

The set of controls that **are** supported could be feature-detectable, via the DOMTokenList.supports("legend") API.

**Comment by AliyanH** [comment]
[geolocation control](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/780) should be a non-default control

**Comment by prushforth** [comment]
We have got the geolocation control now as a no-default control, that you enable with the `controlslist="geolocation"` attribute / `controlsList` setter, so closing.
