### ISSUE TITLE
Detaching then reattaching <mapml-viewer> fails

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#813]
If you try to remove the viewer from the document, and then re-attach it to the DOM, you get an error that results from the element lifecycle callback trying to re-create the shadow root. 

![image](https://user-images.githubusercontent.com/2437285/230158132-0265a305-150c-4160-abe0-e986d7d5c4f8.png)

**Comment by AliyanH** [comment]
I guess the shadow root should get removed on the disconnected callback

**Comment by prushforth** [comment]
Something like that. I guess it depends on what a user/developer's expectations would be for removing and returning the element from the DOM (when does this actually happen, in practice??).  Should the thing retain its state, or be reset?  Probably requires a little research on other elements, like video, etc.
