### ISSUE TITLE
Make sure |Maps for HTML activity is being recorded by w3c cg activity monitor accross all repositories

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#849]
It's not clear that all our activity is being recorded by [this repo](https://github.com/w3c/cg-monitor), which generates [this daily dashboard](https://w3c.github.io/cg-monitor/).  Fix if necessary.

**Comment by prushforth** [comment]
@dontcallmedom any advice you can offer much appreciated.  cheers!

**Comment by dontcallmedom** [comment]
The CG monitor was recently made more robust (where previously it may have been under-reporting activity in some circumstances), and I believe it properly captures activity on the https://github.com/Maps4HTML/ organization repos - although at the moment, the tool focuses on detecting new issues and pull requests, and so wouldn't be reporting commits that are pushed directly to the main branch as distinct new activity.

**Comment by prushforth** [comment]
> wouldn't be reporting commits that are pushed directly to the main branch as distinct new activity.

That's good because we operate using PRs and issues etc, but not direct commits pushed upstream.  We go through the motions of an open source project not only because it's good practice, but also in the hope that other organizations will see value in contributing if the process is (somewhat) transparent.

Anyway, thanks for confirmation.
