### ISSUE TITLE
Removing a unchecked map-feature does not get removed from map

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/Web-Map-Custom-Element#856]
To replicate: 

- Go to this [experiment](https://maps4html.org/experiments/api/map-feature/)
- Click "Add feature"
- Uncheck the "Empty" layer from layer control
- click "Remove feature"
- Recheck the "Empty" layer from layer control
- The layer still gets displayed despite the fact that the associated map-feature has been removed

              noticed another issue just now that I will work on, removing a map-feature when it is unchecked does not work (can be handled in a separate issue).

_Originally posted by @AliyanH in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/841#issuecomment-1548190838_

**Comment by yhy0217** [comment]
Resolved in b472c218014633ed51cc6754b59f3fa652d089cd and #873
