### ISSUE TITLE
Feature Index disappearing on map moves

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#867]
Steps to reproduce:

Enable feature indexing on extension:

![image](https://github.com/Maps4HTML/Web-Map-Custom-Element/assets/2437285/ffb84548-7719-4ce4-9f8d-28d660fd29d7)

Load [this page](https://maps4html.org/experiments/screenreader/restaurants/)

Click on the map with your mouse

-- feature index appears

Drag the map \< 1cm 

Expected behaviour

-- if reticle encompasses different features, set of features in the index changes accordingly

Observed behaviour:

-- reticle disappears
-- feature index disappears

**Comment by yhy0217** [comment]
Resolved in 1ccf35434019b19c8f83704cf05033cb7d771802
