### ISSUE TITLE
Update the xmlns="http://www.w3.org/1999/xhtml/" in all mapml files

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/Web-Map-Custom-Element#894]
After #887 (where map-extent is established as a custom element) we discovered that a few remote files were not working properly this is because the xmlns was set incorrectly and had a trailing back slash. 

We need to update mapml files across **all repos** to remove the trailing back slash, to go from:

xmlns="http://www.w3.org/1999/xhtml/"

to

xmlns="http://www.w3.org/1999/xhtml"

**Comment by yhy0217** [comment]
Resolved in #887
