### ISSUE TITLE
Event handler preventing keyboard operability of the checkbox to control visibility of corresponding layer

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#90]
Opened to discuss this [issue comment](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/88#issuecomment-597200561) narrowly here.

**Comment by Malvoz** [comment]
It seems this is no longer an issue, toggling the checkbox with a keyboard works (tested in Chrome and Firefox). Perhaps it was the small structure change in https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/312 that made this work again.
