### ISSUE TITLE
The extent bound is uncorrectly set, resulting the layer-.zoomTo work unproperly

### ISSUE THREAD

**Issue by yhy0217** [Maps4HTML/Web-Map-Custom-Element#900]
to reproduce:

go to: https://maps4html.org/experiments/vector-tiles/mapml/web-map/

zoom to the layer in the first map > the layer disappears from the viewport

Toggle debug mode on the first map > the extent bound does not match the actual size of the extent

The layer- with the same content but a different projection in the second map does not have the same problem. It will zoom to zoom level 0 when doing a layer-.zoomTo(), as expectation.

**Comment by prushforth** [comment]
Closing as no longer an issue
