### ISSUE TITLE
<map-extent> .extent should use in-scope <map-meta> AND child <map-input>-derived bounds / zoom bounds

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#921]
The \<layer-> element uses child \<map-meta> elements for extent and zoom to define an extent that is added to by layer content. That is, if a \<layer-> has no content, its extent bounds and zoom bounds default to that of the projection; if it has content, the content defines the bounds and zoom bounds, and the projection bounds/zoom bounds aren't taken into account.  (The first, in document order) \<layer-> child \<map-meta> elements for bounds and zoom bounds, if present,  define bounds similar to \<map-extent> and \<map-feature>:  each is one of many contributing elements to bounds and zoom bounds.

In the \<map-extent> case, the bounds and zoom bounds are calculated ONLY through the addition of all the child \<map-link> bounds.  Child \<map-meta> elements are not considered from the \<map-extent> POV.  Each (templated) child \<map-link> element calculates its own bounds and zoom bounds, based on a strategy or algorithm which currently only considers sibling and ancestor \<map-meta> bounds-related elements (name=zoom or name=extent) IFF a bounds and zoom bounds can't be calculated from associated \<map-input>s.  I think this strategy is ok for \<map-link> extent calculation: it gives the author an 'out' from specifying axis min/max on \<map-input> elements, which can be slightly confusing. Entering the extent as `<map-meta name="extent" content="..."></map-meta>` might be slightly easier YMMV.  It can be considered an alternative markup strategy for \<map-link> bounds to keep the templated \<map-link> as simple as possible.

Should \<map-link> directly consider the sibling and/or ancestor \<map-meta>?  

I don't think so, but I do believe that the \<map-extent> bounds  strategy should be updated, to be calculated according to a similar strategy to that used by \<layer-> as described in the first paragraph above, that is, the in-scope extent-contributing \<map-meta> elements should form a baseline extent for the \<map-extent>.

cc @AliyanH

**Comment by prushforth** [comment]
This will require adding a mutation observer to \<map-extent>.  The current observer on \<layer-> [only looks at `childList` mutations, does not include `subtree`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe) type mutations, and it probably shouldn't keep track of `subtree` modifications, maybe it would not perform well.

**Comment by AliyanH** [comment]
> This will require adding a mutation observer to <map-extent>.

Yes that seems like the best option, only other option that comes to mind (if we don't want many mutation observers slowing down our codebase) is to implement this inside of the map-meta connectedcallback which checks what it was appended to (and wait on whenReady) and invokes the parent's method to take it into account. Though I think we already tried this approach and it did not work well for us for some reason.

**Comment by prushforth** [comment]
> I do believe that the <map-extent> bounds strategy should be updated, to be calculated according to a similar strategy to that used by <layer-> as described in the first paragraph above, that is, the in-scope extent-contributing <map-meta> elements should form a baseline extent for the <map-extent>.

We discussed this and we defined "in-scope extent-contributing \<map-meta> elements" to mean \<map-extent> **child** \<map-meta> elements. This was [committed in map-extent.js here](https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/916/commits/9ddc3c21d9885ecd95354fde2a32bf0be9c19d5c).

**Comment by prushforth** [comment]
Available in 0.13.0
