### ISSUE TITLE
`dir="rtl"` bug in layers control

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#970]
Bug in the [RTL map](https://maps4html.org/experiments/i18n/rtl/):

![image](https://github.com/user-attachments/assets/a56ab5d5-82ac-4147-aa9a-e21db24977a7)

Caused by the following styles which seem redundant and safe to remove:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/b1a79c9a26f5989066d5114efea8d0465d28eb92/src/mapml.css#L869-L872

**Comment by prushforth** [comment]
Thanks Robert! Nice to see you.

> Caused by the following styles which seem redundant and safe to remove:

The menu without the offending rule:

![image](https://github.com/user-attachments/assets/624a3ced-2fd7-4b5e-8508-627e0b76f630)

Seems odd to me that sliders don't flip their min/max ends when in rtl mode!
